### ISSUE TITLE
Latest perfect release can't find Foundation

### ISSUE THREAD

**Issue by eimantas** [PerfectlySoft/Perfect#104]
I'm attempting to build hash `a1a9fe27c9a5fef4434c50ede050dea206807423` and this is what I get on Ubuntu 14.04 when making PerfectLib:

```
~/s/P/PerfectLib ❯❯❯ make
swift -frontend -c  NetNamedPipe.swift File.swift Threading.swift LibEvent.swift Bytes.swift FastCGI.swift LogManager.swift NetTCPSSL.swift PerfectServer.swift WebConnection.swift Closeable.swift FastCGIServer.swift Net.swift Utilities.swift MimeReader.swift NetTCP.swift SessionManager.swift WebRequest.swift HTTPServer.swift MimeType.swift PageHandler.swift SQLite.swift WebResponse.swift Dir.swift Mustache.swift PerfectError.swift SysProcess.swift DynamicLoader.swift JSON.swift Utilities-Server.swift Routing.swift StaticFileHandler.swift WebSocketHandler.swift JSONConvertible.swift cURL.swift -primary-file ICU.swift \
		-emit-module-path ./tmp/ICU.swiftmodule \
		-emit-module-doc-path ./tmp/ICU.swiftdoc \
		-emit-dependencies-path ./tmp/ICU.d \
		-emit-reference-dependencies-path ./tmp/ICU.swiftdeps \
		-g -Onone -Xcc -DDEBUG=1 -emit-module -I /usr/include/ -I linked/LibEvent -I linked/OpenSSL_Linux -I linked/ICU -I linked/SQLite3 -I linked/cURL_Linux -module-cache-path /tmp/modulecache -module-name PerfectLib -I linked/LinuxBridge -g -Onone -Xcc -DDEBUG=1 -emit-module -I /usr/include/ -I linked/LibEvent -I linked/OpenSSL_Linux -I linked/ICU -I linked/SQLite3 -I linked/cURL_Linux -module-cache-path /tmp/modulecache -module-name PerfectLib -I linked/LinuxBridge \
		-o ICU.o
SessionManager.swift:26:8: error: no such module 'Foundation'
import Foundation
       ^
make: *** [ICU.o] Error 1
```

Any help is appreciated.

**Comment by kjessup** [comment]
What Swift snapshot are you using? I had no luck using anything which included Foundation with the January 25, 2016 snapshot and had to go back to Jan 11. I see there is a February 3, 2016 release but I haven't tried that one yet.

**Comment by eimantas** [comment]
I'm using snapshot from February 3rd, 2016. It seems that `SessionManager.swift` plainly imports `Foundation` which is not available on Linux. I think the proper import should be for `Glibc`. I'll try to edit that file and see if `PerfectLib` compiles.

**Comment by kjessup** [comment]
It was available though. This all worked fine with Jan 11 and before. Perhaps it was renamed. I'll have to dig up some info.

**Comment by eimantas** [comment]
Including Glibc instead of Foundation didn't help much. There are other places that used Foundation methods. Now I get compilation error on missing `hasPrefix()` method for `String`:

```
swift -frontend -c ICU.swift NetNamedPipe.swift File.swift Threading.swift LibEvent.swift Bytes.swift  LogManager.swift NetTCPSSL.swift PerfectServer.swift WebConnection.swift Closeable.swift FastCGIServer.swift Net.swift Utilities.swift MimeReader.swift NetTCP.swift SessionManager.swift WebRequest.swift HTTPServer.swift MimeType.swift PageHandler.swift SQLite.swift WebResponse.swift Dir.swift Mustache.swift PerfectError.swift SysProcess.swift DynamicLoader.swift JSON.swift Utilities-Server.swift Routing.swift StaticFileHandler.swift WebSocketHandler.swift JSONConvertible.swift cURL.swift -primary-file FastCGI.swift \
		-emit-module-path ./tmp/FastCGI.swiftmodule \
		-emit-module-doc-path ./tmp/FastCGI.swiftdoc \
		-emit-dependencies-path ./tmp/FastCGI.d \
		-emit-reference-dependencies-path ./tmp/FastCGI.swiftdeps \
		-g -Onone -Xcc -DDEBUG=1 -emit-module -I /usr/include/ -I linked/LibEvent -I linked/OpenSSL_Linux -I linked/ICU -I linked/SQLite3 -I linked/cURL_Linux -module-cache-path /tmp/modulecache -module-name PerfectLib -I linked/LinuxBridge -g -Onone -Xcc -DDEBUG=1 -emit-module -I /usr/include/ -I linked/LibEvent -I linked/OpenSSL_Linux -I linked/ICU -I linked/SQLite3 -I linked/cURL_Linux -module-cache-path /tmp/modulecache -module-name PerfectLib -I linked/LinuxBridge \
		-o FastCGI.o
FastCGI.swift:116:41: error: value of type 'String' has no member 'hasPrefix'
                        if contentType == nil || !contentType!.hasPrefix("multipart/form-data") {
                                                  ~~~~~~~~~~~^ ~~~~~~~~~
make: *** [FastCGI.o] Error 1
```

**Comment by kjessup** [comment]
Foundation was included up until the Jan 11 then it seems to have gone away:

/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu15.10/usr/lib/swift/linux/x86_64/Foundation.swiftmodule
/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu15.10/usr/lib/swift/linux/x86_64/Glibc.swiftmodule
/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu15.10/usr/lib/swift/linux/x86_64/Swift.swiftmodule
/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu15.10/usr/lib/swift/linux/x86_64/XCTest.swiftmodule
/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu15.10/usr/lib/swift/pm/PackageDescription.swiftmodule
/swift-2.2-SNAPSHOT-2016-01-06-a-ubuntu15.10/usr/lib/swift/linux/x86_64/Foundation.swiftmodule
/swift-2.2-SNAPSHOT-2016-01-06-a-ubuntu15.10/usr/lib/swift/linux/x86_64/Glibc.swiftmodule
/swift-2.2-SNAPSHOT-2016-01-06-a-ubuntu15.10/usr/lib/swift/linux/x86_64/Swift.swiftmodule
/swift-2.2-SNAPSHOT-2016-01-06-a-ubuntu15.10/usr/lib/swift/linux/x86_64/XCTest.swiftmodule
/swift-2.2-SNAPSHOT-2016-01-06-a-ubuntu15.10/usr/lib/swift/pm/PackageDescription.swiftmodule
/swift-2.2-SNAPSHOT-2016-01-11-a-ubuntu15.10/usr/lib/swift/linux/x86_64/Foundation.swiftmodule
/swift-2.2-SNAPSHOT-2016-01-11-a-ubuntu15.10/usr/lib/swift/linux/x86_64/Glibc.swiftmodule
/swift-2.2-SNAPSHOT-2016-01-11-a-ubuntu15.10/usr/lib/swift/linux/x86_64/Swift.swiftmodule
/swift-2.2-SNAPSHOT-2016-01-11-a-ubuntu15.10/usr/lib/swift/linux/x86_64/XCTest.swiftmodule
/swift-2.2-SNAPSHOT-2016-01-11-a-ubuntu15.10/usr/lib/swift/pm/PackageDescription.swiftmodule
/swift-2.2-SNAPSHOT-2016-01-25-a-ubuntu15.10/usr/lib/swift/linux/x86_64/Glibc.swiftmodule
/swift-2.2-SNAPSHOT-2016-01-25-a-ubuntu15.10/usr/lib/swift/linux/x86_64/Swift.swiftmodule
/swift-2.2-SNAPSHOT-2016-02-03-a-ubuntu15.10/usr/lib/swift/linux/x86_64/Glibc.swiftmodule
/swift-2.2-SNAPSHOT-2016-02-03-a-ubuntu15.10/usr/lib/swift/linux/x86_64/Swift.swiftmodule

Still digging…

**Comment by eimantas** [comment]
It seems this is the commit that removes the foundation: https://github.com/apple/swift/commit/b05e392d75a354500b5ae7c575ef1256dd4a2da1

**Comment by kjessup** [comment]
I think I got it all taken care of. I can now build with the latest snapshot. Give it a try and let me know what you see so we can close this issue. Thank you for your help!

**Comment by rad182** [comment]
I can confirm that the Foundation error is gone now but there's another error I encountered 
https://github.com/PerfectlySoft/Perfect/issues/105

**Comment by eimantas** [comment]
This did seem to take care of the problem, but now I'm getting following errors:

```
cURL.swift:84:13: error: use of unresolved identifier 'CURLOPT_HEADERDATA'
                setOption(CURLOPT_HEADERDATA, v: opaqueMe)
                          ^~~~~~~~~~~~~~~~~~
cURL.swift:85:13: error: use of unresolved identifier 'CURLOPT_WRITEDATA'
                setOption(CURLOPT_WRITEDATA, v: opaqueMe)
                          ^~~~~~~~~~~~~~~~~
cURL.swift:86:13: error: use of unresolved identifier 'CURLOPT_READDATA'
                setOption(CURLOPT_READDATA, v: opaqueMe)
                          ^~~~~~~~~~~~~~~~
make: *** [cURL.o] Error 1
```

**Comment by lokinfey** [comment]
the same problem to me .my os is Ubuntu 14.04

**Comment by pschneider** [comment]
Facing the same problem as @eimantas

**Comment by lokinfey** [comment]
Can you solve it @kjessup

**Comment by johnmorrell** [comment]
I'm hitting this issue too. Until there is a fix you can use checkout from just before this was introduced and it will build at least.

git checkout 0ef42b303fb2cfec79ed95c65f19052aef18fc79

**Comment by lokinfey** [comment]
Wait new build

**Comment by lokinfey** [comment]
I try it but it give me another error @johnmorrell 

make: clang++: Command not found
make: *** [PerfectLib.so] Error 127

**Comment by lokinfey** [comment]
I reinstall clang I can run it now thx

**Comment by tong3jie** [comment]
swift -frontend -c  NetNamedPipe.swift File.swift Threading.swift LibEvent.swift Bytes.swift FastCGI.swift LogManager.swift NetTCPSSL.swift PerfectServer.swift WebConnection.swift Closeable.swift FastCGIServer.swift Net.swift Utilities.swift MimeReader.swift NetTCP.swift SessionManager.swift WebRequest.swift HTTPServer.swift MimeType.swift PageHandler.swift SQLite.swift WebResponse.swift Dir.swift Mustache.swift PerfectError.swift SysProcess.swift DynamicLoader.swift JSON.swift Utilities-Server.swift Routing.swift StaticFileHandler.swift WebSocketHandler.swift JSONConvertible.swift -primary-file ICU.swift \
	-emit-module-path ./tmp/ICU.swiftmodule \
	-emit-module-doc-path ./tmp/ICU.swiftdoc \
	-emit-dependencies-path ./tmp/ICU.d \
	-emit-reference-dependencies-path ./tmp/ICU.swiftdeps \
	-g -Onone -Xcc -DDEBUG=1 -emit-module -I linked/LibEvent -I linked/OpenSSL_Linux -I linked/ICU -I linked/SQLite3 -module-cache-path /tmp/modulecache -module-name PerfectLib -I linked/LinuxBridge -g -Onone -Xcc -DDEBUG=1 -emit-module -I linked/LibEvent -I linked/OpenSSL_Linux -I linked/ICU -I linked/SQLite3 -module-cache-path /tmp/modulecache -module-name PerfectLib -I linked/LinuxBridge \
	-o ICU.o
make: swift: Command not found
makefile:70: recipe for target 'ICU.o' failed
make: *** [ICU.o] Error 127

**Comment by tong3jie** [comment]
Swift version 2.2.1 (swift-2.2.1-RELEASE)
Target: x86_64-unknown-linux-gnu

**Comment by qizt** [comment]
swift -frontend -c  NetNamedPipe.swift File.swift Threading.swift LibEvent.swift Bytes.swift FastCGI.swift LogManager.swift NetTCPSSL.swift PerfectServer.swift WebConnection.swift Closeable.swift FastCGIServer.swift Net.swift Utilities.swift MimeReader.swift NetTCP.swift SessionManager.swift WebRequest.swift HTTPServer.swift MimeType.swift PageHandler.swift SQLite.swift WebResponse.swift Dir.swift Mustache.swift PerfectError.swift SysProcess.swift DynamicLoader.swift JSON.swift Utilities-Server.swift Routing.swift StaticFileHandler.swift WebSocketHandler.swift JSONConvertible.swift cURL.swift HPACK.swift HTTP2.swift NotificationPusher.swift -primary-file ICU.swift \
		-emit-module-path ./tmp/ICU.swiftmodule \
		-emit-module-doc-path ./tmp/ICU.swiftdoc \
		-emit-dependencies-path ./tmp/ICU.d \
		-emit-reference-dependencies-path ./tmp/ICU.swiftdeps \
		-g -Onone -D DEBUG -D Ubuntu_14_04 -emit-module -I /usr/include/ -I linked/LibEvent -I linked/OpenSSL_Linux -I linked/ICU -I linked/SQLite3 -I linked/cURL_Linux -module-cache-path /tmp/modulecache -module-name PerfectLib -I linked/LinuxBridge \
		-o ICU.o
make: swift: Command not found
make: *** [ICU.o] Error 127


Swift version 2.2.1 (swift-2.2.1-RELEASE)
Target: x86_64-unknown-linux-gnu

**Comment by tong3jie** [comment]
juju@ubuntu:~/Perfect/PerfectLib$ sudo make
swift -frontend -c  NetNamedPipe.swift File.swift Threading.swift LibEvent.swift Bytes.swift FastCGI.swift LogManager.swift NetTCPSSL.swift PerfectServer.swift WebConnection.swift Closeable.swift FastCGIServer.swift Net.swift Utilities.swift MimeReader.swift NetTCP.swift SessionManager.swift WebRequest.swift HTTPServer.swift MimeType.swift PageHandler.swift SQLite.swift WebResponse.swift Dir.swift Mustache.swift PerfectError.swift SysProcess.swift DynamicLoader.swift JSON.swift Utilities-Server.swift Routing.swift StaticFileHandler.swift WebSocketHandler.swift JSONConvertible.swift cURL.swift HPACK.swift HTTP2.swift NotificationPusher.swift -primary-file ICU.swift \
	-emit-module-path ./tmp/ICU.swiftmodule \
	-emit-module-doc-path ./tmp/ICU.swiftdoc \
	-emit-dependencies-path ./tmp/ICU.d \
	-emit-reference-dependencies-path ./tmp/ICU.swiftdeps \
	-g -Onone -D DEBUG -D Ubuntu_15_10 -emit-module -I /usr/include/ -I linked/LibEvent -I linked/OpenSSL_Linux -I linked/ICU -I linked/SQLite3 -I linked/cURL_Linux -module-cache-path /tmp/modulecache -module-name PerfectLib -I linked/LinuxBridge \
	-o ICU.o
make: swift: Command not found
makefile:78: recipe for target 'ICU.o' failed
make: *** [ICU.o] Error 127
