### ISSUE TITLE
Feature request: AWS Lambda support

### ISSUE THREAD

**Issue by vince-marco** [PerfectlySoft/Perfect#110]
Not sure what AWS would need to do to make Swift/Perfect available for Lambda development, but I'd love to see this availability.  I would imagine Swift/Perfect already would be usable from EC2.

**Comment by johnmorrell** [comment]
It is relatively straight forward to run on AWS via Docker and ECS.

**Comment by linxyfe** [comment]
@johnmorrell how can Docker and ECS help us ?

**Comment by loopbum** [comment]
@vince-marco _**"I would imagine Swift/Perfect already would be usable from EC2"**_
That's great news. Do you have a gist that goes through the steps? It might be trivial but still useful.

As for Docker, I tried them with Google Containers and they were always failing. Whereas with Amazon EC2 and Ubuntu (Trusty) 14.04 LTS, you can pass ssh -o "ServerAliveInterval 10" when connecting and it will not timeout.

Looking forward to a straightforward setup gist for AWS EC2 Ubuntu 14.04 LTS.

**Comment by Sha0** [comment]
vince-marco: Hello.  If you log into the Amazon EC2 Console[1], the us-east-1 region has a public perfect-ubuntu-1510 Amazon Machine Image (AMI) from owner 106004027494.  Does this information help you?

loopbum: Have you tried the PerfectlySoft Inc. Ubuntu 15.10 Perfect Docker image?  It can be found here[2].

[1] https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Images:sort=name
[2] https://hub.docker.com/r/perfectlysoft/ubuntu/

**Comment by Sha0** [comment]
vince-marco: Hello. If you log into the Amazon EC2 Console[1], the us-east-1 region has a public perfect-ubuntu-1510 Amazon Machine Image (AMI) from owner 106004027494. Does this information help you?

loopbum: Hello.  Have you tried the PerfectlySoft Inc. Ubuntu 15.10 Perfect Docker image? It can be found here[2].

[1] https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Images:sort=name
[2] https://hub.docker.com/r/perfectlysoft/ubuntu/

**Comment by loopbum** [comment]
@Sha0 Although that sounds good, this is just a starter container image for PerfectlySoft.
Wouldn't it then require for me to install the rest of my items:
1 - Anaconda
2 - TensorFlow
3 - Jupyter

Again, correct me if I'm wrong, but Isn't that the primary flow of Docker containers. The image you mention may contain Perfect, but the other 3 still need installing.

So if one starts with any of the other images, you still need to install the other components. I guess Anaconda from continuum.io is a good example for an image because it contains Python 3.5.1 in my scenario and almost all of the important Python packages.

That's why I'm looking for a simple installation process.

**Comment by Sha0** [comment]
loopbum: I'm afraid that I've misunderstood what it is that you're interested in.  Sorry about that.  I don't know what a "setup gist" is.

**Comment by loopbum** [comment]
@Sha0 you mention to vince-macro to reference an Amazon Machine Image. He was asking about Lambda dev, and mentioned installing Perfect on EC2. That's what I'm asking. What are the steps (if you know). I already have an instance running with other software so I'm not interested in a Docker Container or another users AMI file. Do you know what a "gist" is here on github? :-/

**Comment by Sha0** [comment]
loopbum: Yes, I know what a "gist" is, here on GitHub.  Getting Swift and Perfect to be available in your own system will depend on your operating system and its version.  In general, the steps are:
- Extract the right Swift download into the filesystem
- Put the Perfect git repository somewhere, perhaps as a /usr/src/perfect/ directory
- In the Perfect PerfectLib/ directory, read the Linux build notes in the read-me file and run 'make' and 'make install'
- In the Perfect PerfectServer/ directory, read the Linux build notes in the read-me file and run 'make' and 'make install'
- In the Perfect Connectors/ directory, for each module's directory, read the Linux build notes in the read-me file and run 'make', then copy the resulting file.so and file.swiftmodule into somewhere useful, perhaps into the /usr/local/lib/ directory

Only Ubuntu is considered for the Linux build notes, but Fedora, Red Hat, CentOS should have counterparts.

**Comment by loopbum** [comment]
@vince-marco see,
https://medium.com/@gigq/using-swift-in-aws-lambda-6e2a67a27e03#.t1s3jnyas

**Comment by vince-marco** [comment]
I agree with the comments.  Perfect is not needed for implementing AWS Lamdbas.  API Gateway handles all REST request/response interaction.  The JS bootstrapping is a bit hokey, but that is on AWS and cannot be resolved through Perfect.
