### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by lokinfey** [PerfectlySoft/Perfect#116]
I want to add Perfect in swift package in my Package.swift in Ubuntu:

When I set this 

import PackageDescription

let package = Package(
  name:  "demo",
  dependencies: [
    .Package(url:  "https://github.com/PerfectlySoft/Perfect.git", majorVersion: 1),
  ]
)

Then go to terminal type "swift build"  I not download anything I only wait to long like this
<img width="482" alt="2016-02-19 10 49 00" src="https://cloud.githubusercontent.com/assets/4607663/13178672/22d08ee6-d75b-11e5-9982-18621732c67d.png">

then give some error :

error: No version tag found in (/home/lokinfey/code/demo/Packages/Perfect) package. Add a version tag with "git tag" command. Example: "git tag 0.1.0"

Or give me error message

<img width="724" alt="2016-02-19 10 49 22" src="https://cloud.githubusercontent.com/assets/4607663/13178679/30580062-d75b-11e5-82ec-27350ccaf0b9.png">

My aim is I want to build some handler.swift in linux with my Linux IDE .

but it give me that 
main.swift:1:8: error: no such module 'PerfectLib'
import PerfectLib

**Comment by zhuowei** [comment]
@lokinfey I don't think PerfectLib is buildable with Swift Package Manager yet since it contains C++ code; try following the manual installation instructions at https://github.com/PerfectlySoft/Perfect/tree/master/PerfectLib#linux-build-notes

**Comment by lokinfey** [comment]
I think Apple Package Manager not support dynamic lib is a problem

**Comment by kjessup** [comment]
Currently building on all platforms with SPM.
