### ISSUE TITLE
MySQL connection

### ISSUE THREAD

**Issue by sumantimalsina9** [PerfectlySoft/Perfect#118]
I am having trouble while connecting mysql in my perfect project. Can you provide a **sample code**  ?

**Comment by lokinfey** [comment]
import PerfectLib  
import MySQL  
  
  
let HOST = "your sql ip"  
let USER = "your account"  
let PASSWORD = "your password"  
let SCHEME = "your scheme"  
  
public func PerfectServerModuleInit() {  
      
    Routing.Handler.registerGlobally()  
    Routing.Routes["GET", ["/"]] = { (_:WebResponse) in return PerfectHandler() }  
    print("\(Routing.Routes.description)")  
}  
  
//Create a handler for index Route  
class PerfectHandler: RequestHandler {  
      
    func handleRequest(request: WebRequest, response: WebResponse) {  
          
        response.addHeader("Content-Type", value: "application/json")  
        response.addHeader("Content-Type", value: "text/html; charset=utf-8")  
          
        let mysql = MySQL()  
        let connect = mysql.connect(HOST, user: USER, password: PASSWORD)  
        if(connect)  
        {  
            let sres = mysql.selectDatabase(SCHEME)  
            if(sres)  
            {  
                  
                let sres2 = mysql.query("SELECT name,memo FROM Info")  
                  
                if(sres2)  
                {  
                    let results = mysql.storeResults()!  
                      
                      
                      
                    if(results.numRows()==0)  
                    {  
                        do{  
                              
                              
                            let encoder = JSONEncoder()  
                            let data = try encoder.encode(["result": ""])  
                            response.appendBodyString(data)  
                        }  
                        catch{  
                            response.setStatus(500, message: "Could not create data")  
                        }  
                    }  
                    else  
                    {  
                        var dataArray:Array<AnyObject> = []  
                        var dict = Dictionary<String,String>()  
                        while let row = results.next() {  
                              
                            dict["name"]=row[0];  
                            dataArray.append(dict)  
                              
                        }  
                          
                        print(NSJSONSerialization.isValidJSONObject(dataArray))  
                          
                          
                        do {  
                              
                              
                            let dataFinal = try NSJSONSerialization.dataWithJSONObject(dataArray, options:NSJSONWritingOptions(rawValue:0))  
                              
                            let string = NSString(data: dataFinal, encoding: NSUTF8StringEncoding)  
                              
                            let tee : String = string as! String  
                            response.appendBodyString(tee)  
                        }  
                        catch{  
                            response.setStatus(500, message: "Could not create data")  
                        }  
                          
                          
                          
                    }  
                      
                      
                      
                      
                    results.close()  
                }  
            }  
            mysql.close()  
        }  
        response.requestCompletedCallback()  
    }  
}  

if you want to learn more , go to my Chinese blog:
http://blog.csdn.net/kinfey/article/details/50644752

**Comment by sumantimalsina9** [comment]
thank you. Can you give tell me how MVC pattern implies in Perfect Swift?
Also, I want to build a backend for my mobile application.

**Comment by lokinfey** [comment]
okay i will write some tutorials about that . You can see my blog step by step 

http://blog.csdn.net/u014388424/article/category/6092861

**Comment by LucasC53** [comment]
Thanks @lokinfey!

**Comment by lokinfey** [comment]
@sumantimalsina9  this is mvc pattern implies guideline for swift http://blog.csdn.net/kinfey/article/details/50754770

**Comment by iamjono** [comment]
Thanks @lokinfey for helping here.
Closing issue. Thanks!
