### ISSUE TITLE
Suggestion: Object mapping for JSON

### ISSUE THREAD

**Issue by fuxx** [PerfectlySoft/Perfect#12]
Dear Kyle,

thank you first for the effort you already put into this project. I really hope that server-side Swift will take its place in the future. We need someone who start with a project like this and if people like it you will get support for sure.

Besides that i have one suggestion regarding the json serialization/deserialization.
In my projects i use[ ObjectMapper](https://github.com/Hearst-DD/ObjectMapper) from [Hearst](https://github.com/Hearst-DD) as it allows me to write classes and create a mapping of static types and a JSON output or input. Also i can define custom formatters to catch an convert my content on the fly, based on the mapping i defined in my mappable classes.

It would be nice to see an approach like this as it allows us developers to rely on what we define. This kind of approach already works with [AlamofireObjectMapper](https://github.com/tristanhimmelman/AlamofireObjectMapper) and makes it totally easy and safe to handle untyped data in a strongly typed world.

Thanks in advance and good luck,
Stefan

**Comment by bsneed** [comment]
here's a pretty light weight one i've been working on.  https://github.com/TheHolyGrail/Coconut, the ones mentioned are pretty heavy imo.

**Comment by kylebshr** [comment]
I think automatic serializing of classes on each end would be awesome — perhaps using KVC to automatically serialize a class to JSON on the server/client and back to a class on the receiving end. Then you could just do `NetworkManager.fetchClass(classType)`  (extremely pseudocode) and get back instance of those classes. No dealing with manually mapping JSON keys to values, no parsing JSON at all.

**Comment by iamjono** [comment]
Hi all - with the modular changes to Perfect v2, and the fact that you can add your own deps easily now using SPM, I would encourage you to layer this over the top of Perfect rather than work to embed within.
Thanks for the feedback :)
