### ISSUE TITLE
Run server not through Xcode.

### ISSUE THREAD

**Issue by monRo** [PerfectlySoft/Perfect#123]
Its possible to run server as standalone application? Coz i archive project, and then launch app, got error `PerfectServer HTTP cannot be opened because of a problem. Check with the developer to make sure PerfectServer HTTP works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X.`

**Comment by iamjono** [comment]
Hi @monRo - I think this is to do with the v1 release, not the recent refactoring to v2?
Can you confirm? Closing in the meantime, please reopen if still an issue with v2. Thanks!
