### ISSUE TITLE
Refactoring: Investigate Use of external template engine

### ISSUE THREAD

**Issue by alexandros-s** [PerfectlySoft/Perfect#127]
I suggest that the template engine should be decoupled from the framework. We can use a default template engine, loading it as a submodule. That way a developer will have the ability to use the template engine of her choice with a little configuration.

I would prefer depending on an external template engine. [GRMustache](https://github.com/groue/GRMustache.swift) appears that is closer to our own mustache template engine and it would be a good replacement candidate.

I also feel that the following features should investigated:

- [ ] Route gluing a Handler/Controller? with a Template
- [ ] template extensions
- [ ] template partial support

**Comment by iamjono** [comment]
Thanks @alexandros-s - we have in fact done the migration to using Swift 3 & Swift Package Manager.
Using SPM allows exactly what you wish, as we have decoupled things like Mustache to their own modules.
