### ISSUE TITLE
Add LINUX section in examples

### ISSUE THREAD

**Issue by da-na** [PerfectlySoft/Perfect#128]
Hi guys!
I'm very excited to play with your PerfectLibs and I'm currently trying to build my own server on my Linux machine :D I started with examples :) Therefore, I believe it would be great if you could add Linux section in examples, e.g. in [https://github.com/PerfectlySoft/Perfect/tree/master/Examples/Tap%20Tracker#tap-tracker] and include solutions like the one mentioned in #46 ;) 

Same thing with Authenticator Server. To make it work on Linux, one needs to (after `make`) copy the index.mustache, login.mustache and register.mustache to ~/Perfect/PerfectServer/webroot/

**Comment by iamjono** [comment]
I completely agree - this is something we are actively working through.
I'm going to close this though, as it's an active work in progress. Thanks!
