### ISSUE TITLE
Simple Deployment Options

### ISSUE THREAD

**Issue by SeanStephens** [PerfectlySoft/Perfect#138]
One of our goals is to make Perfect both easy to setup for development, but also make it easy to deploy on cloud services. Our current hit-list for build packs/tiles/whatever-you-call-it and detailed instructions for deployment looks like this (in order of preference based on developer feedback);

1) Heroku
2) Cloud Foundry
3) Docker
4) AWS
5) Azure
6) Google Cloud

Anyone interested in helping out? Any additional suggestions for final deployment options?

**Comment by Sha0** [comment]
I have an interest in getting Perfect apps to be easily deployed with Heroku.  If I were to dive into that, would the Perfect community be available for dialogue?

**Comment by SeanStephens** [comment]
Check here as well: https://github.com/kylef/Curassow-example-helloworld

**Comment by SeanStephens** [comment]
Thanks to Sha0, we now have a Heroku Buildpack in place: PerfectlySoft/Perfect-Heroku-Buildpack

Thanks Sha0!

**Comment by Sha0** [comment]
An Ubuntu 15.10 Docker image is now available: https://hub.docker.com/r/perfectlysoft/ubuntu/

**Comment by b20160** [comment]
@Sha0 how do i use the Docker imgae

**Comment by Sha0** [comment]
Hello, b20160!

If you click on the link, a Docker Hub web-page will appear.  On its lower right is a "Docker Pull Command" section.  This is how you can fetch the Docker image.  The image contains Ubuntu 15.10, Swift, and Perfect (including PerfectLib and PerfectServer).

Once fetched, you can use Docker's "run" command to "run" the image: https://docs.docker.com/engine/userguide/containers/dockerizing/

"Inside" a running Perfect Docker, you can go into /usr/src/perfect/ and examine the Examples/ in there.  Or if you have your application available, you can fetch it into the Docker and try to build and run it!

**Comment by linxyfe** [comment]
3) Docker
1、Encounter : /usr/bin/lldb: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
when run "swift" command to REPL

2、No git support


Somebody HELP !!!

**Comment by iamjono** [comment]
Hi @linxyfe I have split your issue off to it's own thread and assigned it to be dealt with.
https://github.com/PerfectlySoft/Perfect/issues/195

Closing the issue.
