### ISSUE TITLE
Correct PostgreSQL module location on linux

### ISSUE THREAD

**Issue by roma86** [PerfectlySoft/Perfect#140]
Hello. Thank you for great product.

I have compiled and run example project URL Routing on ubuntu, but can not figure out how to correctly ling it with PostgreSQL connector. 

I follow instructions in /Connectors/PostgreSQL/README.md and PostgreSQL.so is there. 

Where i should place it or how i should configure project makefile to avoid error
`URL Routing/PerfectHandlers.swift:21:8: error: no such module 'PostgreSQL'`

I tried to add 
`PGSLQ_ROOT = ../../Connectors/PostgreSQL`
And then append it to the `SWIFTC_FLAGS` 
In result it looks:

```
SWIFTC_FLAGS = -frontend -c -module-cache-path $(MODULE_CACHE_PATH) -emit-module -I /usr/local/lib -I $(PERFECT_ROOT)/linked/LibEvent \
	-I $(PERFECT_ROOT)/linked/OpenSSL_Linux -I $(PERFECT_ROOT)/linked/ICU -I $(PERFECT_ROOT)/linked/SQLite3 -I $(PERFECT_ROOT)/linked/LinuxBridge -I $(PERFECT_ROOT)/linked/cURL_Linux \
	-I $(PGSLQ_ROOT)/libpq
```

But get same error. 

Also i have tried to link PostgreSQL.so and PostgreSQL.swiftmodule to /usr/local/lib with same result.

**Comment by keyOfVv** [comment]
I got same kind of issue while working on MongoDB connector. Although eliminated "no such module MongoDB" error after linking both .so & .swiftmodule file into /usr/local/lib, I got "missing module libmongoc" instead. I am pretty sure I had installed MongoDB-C-driver properly. Maybe a correctly configured makefile will solve these issues? Help :j

**Comment by kjessup** [comment]
All modules are currently building properly with SPM.
