### ISSUE TITLE
Where to find PerfectLib.framework

### ISSUE THREAD

**Issue by LanchaBasualdo** [PerfectlySoft/Perfect#143]
I can not find the PerfectLib.framework. Please somebody explain me how to generate it or where to find it

**Comment by roma86** [comment]
@LanchaBasualdo hello. README of each example provide description how to build example projects.

Simplest way just clone all Perfect repo go to the examples folder and open Examples.xcworkspace in xcode. If all you need is build for mac os this word straight froward.

**Comment by kjessup** [comment]
We've moved to using SPM for building and so I'm closing this issue.
