### ISSUE TITLE
HTTP request from server

### ISSUE THREAD

**Issue by SevaUA** [PerfectlySoft/Perfect#145]
Hello
Sorry for noobs question...
How to make http request from server side?
I can not use NSSession (because I dont have foundation on server)
Using of CURL is not so simple...
When I try to use HTTP2Client, I got error: "Unable to write frame"...

**Comment by kjessup** [comment]
Using CURL is your best bet. Most of the Perfect test cases show using CURL in its async mode which is a bit more complex, but the CURL object's `performFully() -> (Int, [UInt8], [UInt8])` function provides the easiest interface. The result is the HTTP result code, header bytes and body bytes for you to do whatever you will with. The testCURLHeader test case shows it's usage.

The HTTP2Client could work in theory if you were for sure talking to an always-HTTP2 server, but it's very Apple Push Notification specific and has not been tested against any other HTTP2 servers.
