### ISSUE TITLE
FireFox can't connect to Perfect WebSocket Server.

### ISSUE THREAD

**Issue by wuqiong** [PerfectlySoft/Perfect#146]
FireFox can't connect to Perfect WebSocket Server. Tested Firefox Version is 45.0.1, other version might be the same.
Because Firefox send the request with `Connection` header `keep-alive, Upgrade`, not as the `WebSocketHandler.swift` #292 line exactly checked `Upgrade`.

```
where upgrade.lowercaseString == "websocket" && connection.lowercaseString == "upgrade" else {
... ...
```

But,
The RFC-6455 spec, Section 4.1 states ...

   6.   The request MUST contain a |Connection| header field whose value
        MUST **include** the "Upgrade" token.

which means that multi-value Connection header is legitimate and needs to be handled properly.
so, FireFox actions right.

**Comment by kjessup** [comment]
Thank you! I'm going to target fixing this for 1.1 and will backport it to a new 1.0.1 branch. I'll close this when completed.
