### ISSUE TITLE
File.swift:22:8: error: could not build Objective-C module 'LinuxBridge' import LinuxBridge

### ISSUE THREAD

**Issue by j22chan** [PerfectlySoft/Perfect#149]
Trying to build PerfectLib by calling 'make', but get this compile error:

```
/home/ubuntu/Perfect/PerfectLib/linked/LinuxBridge/../../LinuxBridge.h:14:40: error: declaration of 'pthread_cond_t' must be imported from module 'SwiftGlibc.C.signal' before it is required
int pthread_cond_timedwait_relative_np(pthread_cond_t * cond, pthread_mutex_t * mutx, const struct timespec * tmspec);
                                       ^
/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h:153:3: note: previous declaration is here
} pthread_cond_t;
  ^
File.swift:22:8: error: could not build Objective-C module 'LinuxBridge'
import LinuxBridge
```
I'm using swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a-ubuntu14.04

**Comment by wuqiong** [comment]
swift-DEVELOPMENT-SNAPSHOT-2016-03-24-a-ubuntu14.04  might be Swift 3.0 dev. you should to use swift 2.2 version.

**Comment by j22chan** [comment]
I think it would be really helpful if you updated the doc to point to 
the right swift images to use to get Perfect working

**Comment by nsleader** [comment]
Same problem
Ubuntu 14.04
swift-2.2-SNAPSHOT-2016-03-01-a-ubuntu14.04.tar.gz

**Comment by kjessup** [comment]
Currently building on all platforms with SPM.
