### ISSUE TITLE
How do we create our own server with PerfectLib ?

### ISSUE THREAD

**Issue by linxyfe** [PerfectlySoft/Perfect#150]
Now we can see there are some working examples , but I still don't get how we can create our own server with Perfect, is there any Tutorial ? or will it be added to README ? 
BTW, Perfect is now working on Linux, is there any chance we can build a server on linux too ?

**Comment by LucasC53** [comment]
Hi @linxyfe,

We're in the process of making some tutorial videos, but in the meantime, would any of these tutorials written by other developers in the community help?

- http://code-me-dirty.blogspot.co.uk/2016/02/creating-perfect-swift-server.html
- http://www.chrismanahan.com/creating-a-web-service-swift-perfect
- Create Your Perfect project on Linux (#3): http://blog.csdn.net/kinfey/article/details/50683127
- Running Perfect in Linux (#2): http://blog.csdn.net/kinfey/article/details/50664353
- Project Perfect let Swift in the server up and running - Introduction (#1): http://blog.csdn.net/kinfey/article/details/50644752

**Comment by linxyfe** [comment]
@LucasC53 oh,thx a lot. I will check it.

**Comment by maxandmax** [comment]
big project. what i realy can do with this ui & webserver ?

**Comment by wuqiong** [comment]
https://selfstore.io/products/596  I write a small book with Perfect.
