### ISSUE TITLE
Viewing/Playing MP4 Video on Server, Crashes Server

### ISSUE THREAD

**Issue by FibonacciRedstone** [PerfectlySoft/Perfect#155]
Whenever I play a MP4 video that is hosted on my server, even without m,y module loaded, that server pauses and is un able to play the video. Is anyone else having this issue and if not, what am I doing incorrectly

**Comment by FibonacciRedstone** [comment]
Any Help?

**Comment by kjessup** [comment]
I think I know what the problem is and I will be targeting this today.

**Comment by kjessup** [comment]
With the newest changes on master, this is now working properly. Thank you for the report and please respond if you still see issues. Note that these changes have not been back ported to the 1.0.1 branch.

**Comment by FibonacciRedstone** [comment]
Thank you! I appreciate this very much

-Ben Perkins
