### ISSUE TITLE
Please can we reduce the spaces in tab from 8 to 4 or even 2 (better)

### ISSUE THREAD

**Issue by kajalsinha** [PerfectlySoft/Perfect#156]
Hi,

I observed that the tab is 8 characters. It makes the code a little difficult to read no matter how wide you make your editor. As we use the functional features of swift (or any other functional programming language), we will often see a lot of unavoidable nesting and thus more deeper tabs.

Please, can perfect team make this move to reduce the space count to 4 spaces ? I have seen 2 spaces look even better but that is my personal view. 4 spaces is most of the developers will agree I think.

Thanks
Kajal

**Comment by kjessup** [comment]
That's odd. I only use the 4 space tabs. Do you see this problem in all the files?

**Comment by rymcol** [comment]
I see them as standard 4 space tabs on 10.11.5 Beta (15F28b) running Xcode  7.3.1 (7D1012/GM Seed)

**Comment by kajalsinha** [comment]
Hi here is an example file : 
Perfect/Sources/PerfectLib/FastCGI.swift

Please look within github editor as well.

**Comment by iamjono** [comment]
Hi @kajalsinha - Looking at the current state of the source files both in the GitHub editor and Xcode 8, I am seeing tab-based spacing.

All I can assume is that the source formatting has been updated since raising the issue.
Thanks for bringing it to our attention!
