### ISSUE TITLE
How can i build project success in Ubuntu when i use foundation module

### ISSUE THREAD

**Issue by irobbin1024** [PerfectlySoft/Perfect#163]
for example, Perfect example URL Routing,  add `import Foundation` to file `PerfectHandlers.swift`.

exec `make`, but i got error like this

```
URL Routing/PerfectHandlers.swift:22:8: error: no such module 'Foundation'
import Foundation
       ^
makefile:21: recipe for target 'URLRouting' failed
make: *** [URLRouting] Error 1

```

system is Ubuntu 15.10, Swift  version is 2.2.1-dev

how fix this error?

**Comment by abjurato** [comment]
As far as I've understood, Foundation lib is not part of Swift2.2 on linux.
I've found [Foundation Project](https://github.com/apple/swift-corelibs-foundation) on github, but it is claimed to be ready for production by Swift3 release:
> This project is in the early stages of development. It is not yet ready for production use, but it is ready for contributions. It is scheduled to be part of the Swift 3 release.

**Comment by robertBojor** [comment]
Yep, including Foundation will not work on Linux - works perfectly on Mac, but how many people are going to host their API back-end on a Mac...

Also, stay away from any NS type of declaration or types - they will not compile.

**Comment by iamjono** [comment]
Hi @irobbin1024 - yes we're going to have to wait for Swift 3 for this to be available on Linux from what I understand. They're doing some good work over here https://github.com/apple/swift-corelibs-foundation but we have to be patient I think!
