### ISSUE TITLE
"array cannot be bridged from Objective-C" when encode [[String: AnyObject]] object with jsonEncoder.

### ISSUE THREAD

**Issue by qizt** [PerfectlySoft/Perfect#165]
let respObject:[[String: AnyObject]] =
	[
		["foo": 1, "bar": "foo"],
		["bar": 2, "foo": "bar"]
	]
    let jsonEncoder = JSONEncoder()
    let respString = try jsonEncoder.encode(respObject)

When I tried to encode dictionary array with jsonEncoder, I encounter this error:

**fatal error: array cannot be bridged from Objective-C**

If this is a inappropriate way to responding JSON, just let me know, I would appreciate it.

![screen shot 2016-05-04 at 23 05 53](https://cloud.githubusercontent.com/assets/7324708/15035890/7bdef8ba-124d-11e6-8f18-61d393da6b0d.png)

**Comment by abjurato** [comment]
try `let respObject:[JSONValue]` instead of `[[String: AnyObject]]`

**Comment by rymcol** [comment]
@qizt without any pretty formatting, you can achieve that with:

`
func handleRequest(request: WebRequest, response: WebResponse) {
        
        let obj1:[String: JSONValue] = ["foo": 1, "bar": "foo"]
        let obj2:[String: JSONValue] = ["party": "yes", "hard": "yes"]
        
        let jsonObjects = [obj1, obj2]
        
        for object in jsonObjects {
            let respObject: [String: JSONValue] = object
            
            let jsonEncoder = JSONEncoder()
            
            do {
                let respString = try jsonEncoder.encode(respObject)
                response.appendBodyString("\(respString),")
            } catch let err as NSError {
                print(err.debugDescription)
            }
        }
        
        
        
        response.requestCompletedCallback()
    }
`

The encoder likes Dictionary<String, JSONValue>, not an array of those.

**Comment by qizt** [comment]
@abjurato @rymcol  Thank you guys!

I tried to declare values as JSONValue and it worked. Values that I want to encode, they should be declared as JSONValue indeed.

I did make a low level mistake.

Since this is my problem not Perfect's, I'm gonna close this issue.

You guys are awesome!

**Comment by rymcol** [comment]
# Encoding JSON!

Issue #165 by @qizt had a good question: "How do I encode JSON"

This was a relatively short topic, so I took some time on my lunch break today to try to answer that in context with how it was asked in a _New Video_. 

You can watch it at: https://youtu.be/EwoXL_ZnA3s

Thanks!
