### ISSUE TITLE
Warning: Class XXX is implemented in both [PATH1] and [PATH2]. One of the two will be used. Which one is undefined. 

### ISSUE THREAD

**Issue by KevinGong2013** [PerfectlySoft/Perfect#169]
Download PerfectStarter, select PerfectServerHTTP schema, build && run then I am getting runtime warnings like this:

`objc[39482]: Class _TtC10Foundation15NSSimpleCString is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftFoundation.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtC10Foundation16NSConstantString is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftFoundation.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtC10Foundation15NSFastGenerator is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftFoundation.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCE10FoundationCSo12NSDictionary9Generator is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftFoundation.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs18_EmptyArrayStorage is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs24_ContiguousArrayStorage1 is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs18_CocoaSetGenerator is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs25_CocoaDictionaryGenerator is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs17NonObjectiveCBase is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs17_stdlib_AtomicInt is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs19_SwiftNativeNSArray is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs24_SwiftNativeNSDictionary is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs17_SwiftNativeNSSet is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs24_SwiftNativeNSEnumerator is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs31_stdlib_ReturnAutoreleasedDummy is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs20_SwiftNativeNSString is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs19_NSContiguousString is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs40_SwiftNativeNSArrayWithContiguousStorage is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs21_SwiftDeferredNSArray is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs27_ContiguousArrayStorageBase is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs17_AnyGeneratorBase is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _TtCs13VaListBuilder is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _SwiftNativeNSError is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class SwiftObject is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _SwiftNativeNSArrayBase is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _SwiftNativeNSDictionaryBase is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _SwiftNativeNSSetBase is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _SwiftNativeNSStringBase is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
objc[39482]: Class _SwiftNativeNSEnumeratorBase is implemented in both /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/PerfectLib.framework/Versions/A/Frameworks/libswiftCore.dylib and /Users/Kevin/Library/Developer/Xcode/DerivedData/Perfect-flwaeharqdqqkpfoycqsdvdbnwjh/Build/Products/Debug/perfectserverhttp. One of the two will be used. Which one is undefined.
Load libs from: ./PerfectLibraries/
Starting HTTP server on 0.0.0.0:8181 with document root ./webroot/`

Seems an issue with Swift commandline applications, anyone has any suggestions?

**Comment by nt827** [comment]
I experience this same issue with the MySQL connector. As I am rather new to OS X and Xcode, I suspect the issue is caused by my build settings.

I find the entire "Perfect" project very intriguing... and would like to implement it. My thoughts, though, is to walk before I run. First, I'm looking to build a command-line project to interact with my MySQL db's. Once I've got that up and running, I'll move on to the server implementation.

I was once told, "Ignorance is curable... stupidity, is not". I aspire, at least, to the former... but too frequently I fall into the latter. I'll keep at it... trying to figure out why I get the duplicate loading of dynamic libraries.

It would be fantastic if some of the more savvy developers would give some direction to proper build settings.  :-)

**Comment by iamjono** [comment]
Hi @KevinGong2013, @nt827 - it looks like you're using an old version of Perfect here (v1). We are currently focussing our efforts on Perfect 2, which works with Swift 3.

While I realize our docs are not updated for usage yet, I encourage you to have a look at this repo: https://github.com/PerfectlySoft/Perfect-MySQL - also the MongoDB one, which I added a few usage notes to: https://github.com/PerfectlySoft/Perfect-MongoDB

The tests in the Perfect-MySQL project may help you get things going with Perfect 2 - however please follow the steps closely in the main Perfect repo for getting your Xcode 8 and Swift 3 working correctly together.

Thanks!
Jono
