### ISSUE TITLE
Deploy on AWS?

### ISSUE THREAD

**Issue by AndrewSB** [PerfectlySoft/Perfect#17]
I'm assuming this can't be deployed to a real production server yet, since it can't run on linux.
Is that something that is only reconcilable after Apple open sources the language?

Nevertheless, not being able to scale the servers made is definitely an issue.

**Comment by marinehero** [comment]
Your assumption is correct. If you look at the code you will see that it has Xcode projects. 

My assumption is that this project is for those who want to prepare in advance and will change the minute Apple makes Swift available on Linux.

Guess you can expect a lot of changes down the line.

**Comment by AndrewSB** [comment]
looking forward to when Apple makes that shift

**Comment by kjessup** [comment]
Yes, we will be making changes to accommodate Linux as soon as Apple open sources. After we get things running and tested Linux you would be able to deploy on AWS. We plan on doing pre-configured AWS server images, though you will certainly be able to do the installs yourself.

**Comment by AndrewSB** [comment]
👌

**Comment by DaidoujiChen** [comment]
:+1:

**Comment by andrelrs** [comment]
Hi guys, its suportes Aws now?

cc @AndrewSB @kjessup

**Comment by BleuGamer** [comment]
I've run a test server on aws just fine. It's a little tricky, easiest on a custom ec2 with a startup service. Can be done on beanstalk with docker.

**Comment by dsp1589** [comment]
@BleuGamer How did you deploy the project in AWS. Any links/docs? 
I just created an perfect-ubuntu AMI in aws. Not sure how to push the code. I see perfectserver and perfectlib are there in /usr/src/perfect. Any help much appreciated.

**Comment by robertBojor** [comment]
If it's a single EC2 instance you could deploy the code using git and a
post-receive hook to do all the work once the code is up.

If you went with an EBS, deploy everything through Docker, works Perfectly
😉

On Wednesday, 8 June 2016, Deepak K <notifications@github.com> wrote:

> @dsp1589 <https://github.com/dsp1589> exactly at your stage now. You made
> any progress on that.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PerfectlySoft/Perfect/issues/17#issuecomment-224431934>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACZaBppiD3l8QelydlGhE8uytClZDMe5ks5qJe41gaJpZM4Gq4uM>
> .
>


-- 
Kind regards,
Robert Bojor
Mobile & Web Developer
http://www.robertbojor.com/
