### ISSUE TITLE
Deploy on Heroku with MySQL connector.

### ISSUE THREAD

**Issue by VGudenko** [PerfectlySoft/Perfect#172]
Hello,

I made a small test project using Perfect and MySQL connector.
And now I'm trying to deploy it on Heroku.
But, unfortunately, I get this error:

`remote: -----> Making application        
remote:        Build failure: make        
remote: -----> Log        
remote: /tmp/buildpack20160512-162-1dwu72e        
remote: swift -frontend -c -g -Onone -Xcc -DDEBUG=1 -module-cache-path /tmp/modulecache -emit-module -I /app/.delta/usr/local/lib -I /app/.delta/usr/include -I /app/.delta/usr/include/x86_64-linux-gnu -I /app/.delta/usr/src/perfect/PerfectLib/linked/LibEvent -I /app/.delta/usr/src/perfect/PerfectLib/linked/OpenSSL -I /app/.delta/usr/src/perfect/PerfectLib/linked/ICU -I /app/.delta/usr/src/perfect/PerfectLib/linked/SQLite3 -I /app/.delta/usr/src/perfect/PerfectLib/linked/LinuxBridge -I /app/.delta/usr/src/perfect/PerfectLib/linked/cURL_Linux InsaneByte/Main.swift InsaneByte/DataManager/DataObjects/Person.swift InsaneByte/DataManager/DBManager.swift InsaneByte/ErrorTypes/DataObjectErrors.swift InsaneByte/ErrorTypes/DBManagerErrors.swift InsaneByte/Handlers/ApiMethodsHandler.swift InsaneByte/Handlers/DELETEPersonHandler.swift InsaneByte/Handlers/GETPersonHandler.swift InsaneByte/Handlers/POSTPersonHandler.swift InsaneByte/Handlers/PUTPersonHandler.swift -o InsaneByte.o -module-name InsaneByte -emit-module-path InsaneByte.swiftmodule        
remote: /app/.delta/usr/src/perfect/Connectors/MySQL/../../PerfectLib/linked/OpenSSL_Linux/module.map:1:8: error: redefinition of module 'OpenSSL'        
remote: module OpenSSL [system] {        
remote:        ^        
remote: /app/.delta/usr/src/perfect/PerfectLib/linked/OpenSSL/module.map:1:8: note: previously defined here        
remote: module OpenSSL [system] {        
remote:        ^        
remote: /app/.delta/usr/src/perfect/Connectors/MySQL/../../PerfectLib/linked/OpenSSL_Linux/module.map:1:8: error: redefinition of module 'OpenSSL'        
remote: module OpenSSL [system] {        
remote:        ^        
remote: /app/.delta/usr/src/perfect/PerfectLib/linked/OpenSSL/module.map:1:8: note: previously defined here        
remote: module OpenSSL [system] {        
remote:        ^        
remote: <unknown>:0: error: could not build Objective-C module 'libmysqlclient'        
remote: make: *** [InsaneByte] Error 1        
remote: 
remote:  !     Push rejected, failed to compile Perfect app        
remote: 
remote: Verifying deploy...        
remote: 
remote: !	Push rejected to insanebyte-perfect.        
remote: `

I'm sure, that this issue is related to my makefile.
[makefile.zip](https://github.com/PerfectlySoft/Perfect/files/261492/makefile.zip)

Could any body help my with it?

King regards

**Comment by johnnst** [comment]
I am running into a similar issue with PostgreSQL on Heroku.

remote:        Ok. Ubuntu 14.04 found
remote: -----> Setting environment
remote:        Ok
remote: -----> Ensuring cache directory
remote:        Ok
remote: -----> Generating profile script
remote:        Ok
remote: -----> Setting paths
remote:        Ok
remote: -----> Checking dependencies
remote:        Dependencies cached
remote:        Ok
remote: -----> Installing build dependencies into build environment
remote:        Ok
remote: -----> Making application
remote:        Build failure: make
remote: -----> Log
remote: /tmp/buildpack20160520-170-1ulrxi2
remote: swift -frontend -c -g -Onone -Xcc -DDEBUG=1 -module-cache-path /tmp/modulecache -emit-module -I /app/.delta/usr/local/lib -I /app/.delta/usr/include -I /app/.delta/usr/include/x86_64-linux-gnu -I /app/.delta/usr/src/perfect/PerfectLib/linked/LibEvent -I /app/.delta/usr/src/perfect/PerfectLib/linked/OpenSSL -I /app/.delta/usr/src/perfect/PerfectLib/linked/ICU -I /app/.delta/usr/src/perfect/PerfectLib/linked/SQLite3 -I /app/.delta/usr/src/perfect/PerfectLib/linked/LinuxBridge -I /app/.delta/usr/src/perfect/PerfectLib/linked/cURL_Linux "PerfectFavor/SJFFavorHandler.swift" -o PerfectFavor.o -module-name PerfectFavor -emit-module-path PerfectFavor.swiftmodule
remote: /app/.delta/usr/src/perfect/Connectors/PostgreSQL/../../PerfectLib/linked/OpenSSL_Linux/module.map:1:8: error: redefinition of module 'OpenSSL'
remote: module OpenSSL [system] {
remote:        ^
remote: /app/.delta/usr/src/perfect/PerfectLib/linked/OpenSSL/module.map:1:8: note: previously defined here
remote: module OpenSSL [system] {
remote:        ^
remote: /app/.delta/usr/src/perfect/Connectors/PostgreSQL/../../PerfectLib/linked/OpenSSL_Linux/module.map:1:8: error: redefinition of module 'OpenSSL'
remote: module OpenSSL [system] {
remote:        ^
remote: /app/.delta/usr/src/perfect/PerfectLib/linked/OpenSSL/module.map:1:8: note: previously defined here
remote: module OpenSSL [system] {
remote:        ^
remote: <unknown>:0: error: could not build Objective-C module 'libpq'

Thinking out loud, I think it just doesn't like the fact that it has the same module in both the PostgreSQL and PerfectLib frameworks.

**Comment by Sha0** [comment]
Hello!  Could you please add:

  -v

to your SWIFTC_FLAGS and then share the results?  It's not yet clear to me why the OpenSSL module is being defined twice.

**Comment by Sha0** [comment]
The primary developer for Perfect has suggested adjusting the following adjustment, from:

    -I $(PERFECT_ROOT)/linked/OpenSSL

to:

    -I $(PERFECT_ROOT)/linked/OpenSSL_Linux

Please share your result!

**Comment by Sha0** [comment]
The primary developer for Perfect has suggested the following makefile adjustment, from:

    -I $(PERFECT_ROOT)/linked/OpenSSL

to:

    -I $(PERFECT_ROOT)/linked/OpenSSL_Linux

Please share your result!

**Comment by richardhouta** [comment]
Someone has a makeFile example for mysql ?

**Comment by iamjono** [comment]
@VGudenko and @johnnst - did the suggestions from @Sha0 help?
Closing for now, please reopen if you have more information. Thanks!

**Comment by iamjono** [comment]
@richardhouta - if you could open a separate issue with specifics of what you're after that would be great.
Thanks!
