### ISSUE TITLE
MimeType.o error

### ISSUE THREAD

**Issue by lokinfey** [PerfectlySoft/Perfect#174]
~/Dev/swift-2.2-RELEASE-ubuntu14.04/usr/bin/swift -frontend -c ICU.swift NetNamedPipe.swift File.swift Threading.swift LibEvent.swift Bytes.swift FastCGI.swift LogManager.swift NetTCPSSL.swift PerfectServer.swift WebConnection.swift Closeable.swift FastCGIServer.swift Net.swift Utilities.swift MimeReader.swift NetTCP.swift SessionManager.swift WebRequest.swift HTTPServer.swift  PageHandler.swift SQLite.swift WebResponse.swift Dir.swift Mustache.swift PerfectError.swift SysProcess.swift DynamicLoader.swift JSON.swift Utilities-Server.swift Routing.swift StaticFileHandler.swift WebSocketHandler.swift JSONConvertible.swift cURL.swift HPACK.swift HTTP2.swift NotificationPusher.swift -primary-file MimeType.swift \
                -emit-module-path ./tmp/MimeType.swiftmodule \
                -emit-module-doc-path ./tmp/MimeType.swiftdoc \
                -emit-dependencies-path ./tmp/MimeType.d \
                -emit-reference-dependencies-path ./tmp/MimeType.swiftdeps \
                -g -Onone -D DEBUG -D Ubuntu_14_04 -emit-module -I /usr/include/ -I linked/LibEvent -I linked/OpenSSL_Linux -I linked/ICU -I linked/SQLite3 -I linked/cURL_Linux -module-cache-path /tmp/modulecache -module-name PerfectLib -I linked/LinuxBridge \
                -o MimeType.o
Segmentation fault (core dumped)
make: *** [MimeType.o] Error 139

**Comment by kjessup** [comment]
Currently building on all platforms with SPM.
