### ISSUE TITLE
Perfect Server make fail

### ISSUE THREAD

**Issue by lokinfey** [PerfectlySoft/Perfect#175]
I use ubuntu on Windows . I can compile PerfectLib but when I compile PerfectServer fail . It give me this error :
~/Dev/swift-2.2-RELEASE-ubuntu14.04/usr/bin/swift -frontend -g -Onone -Xcc -DDEBUG=1 -c -module-cache-path /tmp/modulecache -emit-module -I /usr/local/lib -I ../PerfectLib/linked/LibEvent -I ../PerfectLib/linked/OpenSSL -I ../PerfectLib/linked/ICU -I ../PerfectLib/linked/SQLite3 -I ../PerfectLib/linked/LinuxBridge -I ../PerfectLib/linked/cURL_Linux main.swift main_http.swift -o perfectserverhttp.o -module-name perfectserverhttp -emit-module-path perfectserverhttp.swiftmodule
clang++ -L/home/kinfey/Dev/swift-2.2-RELEASE-ubuntu14.04/usr/lib/swift/linux -g -luuid -lcurl -lswiftCore -lswiftGlibc /usr/local/lib/PerfectLib.so -Xlinker -rpath -Xlinker /home/kinfey/Dev/swift-2.2-RELEASE-ubuntu14.04/usr/lib/swift/linux perfectserverhttp.o -o perfectserverhttp
/usr/local/lib/PerfectLib.so: undefined reference to `u_isalnum_55'
/usr/local/lib/PerfectLib.so: undefined reference to `udat_format_55'
/usr/local/lib/PerfectLib.so: undefined reference to `udat_close_55'
/usr/local/lib/PerfectLib.so: undefined reference to `u_isWhitespace_55'
/usr/local/lib/PerfectLib.so: undefined reference to `udat_open_55'
/usr/local/lib/PerfectLib.so: undefined reference to `u_errorName_55'
/usr/local/lib/PerfectLib.so: undefined reference to `ucal_getNow_55'
/usr/local/lib/PerfectLib.so: undefined reference to `udat_parse_55'
/usr/local/lib/PerfectLib.so: undefined reference to `u_isdigit_55'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [perfectserverhttp] Error 1

**Comment by kjessup** [comment]
Currently building on all platforms with SPM.
