### ISSUE TITLE
JSONConvertible missing from PerfectLibiOS target

### ISSUE THREAD

**Issue by profburke** [PerfectlySoft/Perfect#176]
Seems that things have been re-arranged on master in preparation for SPM. But in the release-1.0, JSONConvertible.swift only belongs to the PerfectLibOSX target. So you get unknown class errors if you try and use it in an iOS app.

Solution is simple: open up JSONCovertble.swift in Xcode, command-option-1 to get the file inspector and click the checkbox next to PerfectLibiOS.

**Comment by iamjono** [comment]
Hi @profburke we're shifting all focus to the Perfect v2 release... 
Thanks!
