### ISSUE TITLE
About Swift 3.0 ?

### ISSUE THREAD

**Issue by Barneybook** [PerfectlySoft/Perfect#177]
will support 2.0 and 3.0??

**Comment by rymcol** [comment]
@Barneybook support for 3.0 is on the way.

**Comment by kjessup** [comment]
The master branch supports 2.2.x and 3.0 on OSX. It supports 3.0 on Linux. All Swift Package Manager support is 3.0 only. By 3.0 I mean the last May 9th snapshot.
