### ISSUE TITLE
How to use the Routing and mustaches at the same time?

### ISSUE THREAD

**Issue by nsleader** [PerfectlySoft/Perfect#179]
If you use Routing:
```
Routing.Handler.registerGlobally()
Routing.Routes["GET", ["/", "index.html"] ] = { (_:WebResponse) in return IndexHandler() }
```
mustache not working.

If you use Mustache (PageHandlerRegistry):
```
PageHandlerRegistry.addPageHandler("LoginHandler") {
		(r:WebResponse) -> PageHandler in
		return LoginHandler()
}
```
routing (Routing.Routes) not working!

**Comment by rymcol** [comment]
@nsleader I'm not sure why you would do that?

Mustache is a physical file, much like a .html file. It is copied to the webroot and calls it's handler class through the addPageHandler method when it accessed. Adding a route would override that behavior and serve whatever is in the IndexHandler class instead of the template. 

Perhaps you could give us an example of what you might be trying to accomplish and/or more code?

**Comment by nsleader** [comment]
@rymcol 
Example: https://github.com/nsleader/perfect-routing
The basic idea is to use a mustache templates and routes for API

**Comment by kjessup** [comment]
It was difficult to use both systems in the 1.0 API. This has been rectified for the new upcoming version. Take a look at the code for [Upload Enumerator](https://github.com/PerfectlySoft/PerfectExample-UploadEnumerator). It shows using routes and Mustache at the same time by passing the request to the mustacheRequest function. [UploadHandler.swift](https://github.com/PerfectlySoft/PerfectExample-UploadEnumerator/blob/master/Sources/UploadHandler.swift).

**Comment by nsleader** [comment]
@kjessup 
PerfectLib 1.0 does not allow it?
Thank you.

**Comment by kjessup** [comment]
It does permit this, but it is a bit more cumbersome compared to the master (1.1) branch. Look at the PerfectLibTests.swift : testMustacheParser1 [test](https://github.com/PerfectlySoft/Perfect/blob/release-1.0.1/PerfectLib/PerfectLibTests/PerfectLibTests.swift). It shows feeding the bytes, which would be read from the mustache file, into the template and getting the resulting string.

Here's a gist showing how it works, given an existing index.mustache [Example](https://gist.github.com/kjessup/605a4aace3d37591d1aba34d8f4c786f)

This has all been streamlined in the new code do to exactly what you are asking for, FWIW.
