### ISSUE TITLE
Dependency manager integration

### ISSUE THREAD

**Issue by sergdort** [PerfectlySoft/Perfect#18]
Hi, @kjessup first of all let me say that I very like and enjoy of your project!

But is there going to be some CocoaPods or Carthage integrations?

**Comment by cwoloszynski** [comment]
Can I suggest using the package manager that Apple included in Swift's open source release?

**Comment by kradalby** [comment]
+1 for @cwoloszynski suggestion.

**Comment by DaidoujiChen** [comment]
agree @cwoloszynski

**Comment by jhoughjr** [comment]
+1 for CocoaPods and swift package manager here.

**Comment by SeanStephens** [comment]
Definitely, we plan on supporting CocoaPods and Carthage - and eventually SPM. Also on the table - Homebrew and Apt.

**Comment by TofPlay** [comment]
@SeanStephens any news about Carthage support?

**Comment by SeanStephens** [comment]
We did an online vote, and SPM won - so we have been focused there. We have been heavily focused on re-modularizing, and wanted to make sure these core changes (amongst others) were in place ASAP.

Let me circle back to the team and let you know where it falls on our road map - give me a week or so to get back to you.

**Comment by GJNilsen** [comment]
1. SPM is/will be cross platform.
2. Carthage + CocoaPods got Sherlocked.

Swift will be around, its supported by a big company investing billions into the language and the ecosystem around it is getting better and stronger every day.
Going for SPM is the best decision IMO.

**Comment by TofPlay** [comment]
@GJNilsen I agree soon or later SPM with replace Carthage and CocoaPods. But obviously not before end of 2016 (I think probably not before the first quarter 2017). Currently SPM is still developing and will be available only with Swift 3. What will we do during those 7 months?

**Comment by GJNilsen** [comment]
@TofPlay first, Swift 3 will almost certainly be released together with iOS 10, this fall, so some months without a dependency manager is correct. But isn't there enough task already to use manpower on with this project? Does someone really want to implement something that will be outdated in some months?
Second, I strongly believe code that depends on other code to be downloaded just to be able to build a project, has nothing to do in the project to begin with. Its so easy to forget what happened in March, when a big bag of hurt was opened and the a lot of NodeJS apps felt the wrath of the falling house of card thats called [npm](http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos).
Thats why I feel the only dependency manager is the one that has a solid backing. The sherlocked ones do have some backing, but a lot of that will probably vanish as soon as SPM is released.

**Comment by iamjono** [comment]
I'm closing out the thread based on the integration with SPM - this is already available for the most recent builds of Swift 3, and the master branch projects and modules for the upcoming release of Perfect.
For further discussion, please join us on the Perfect Gitter channel 
[![Gitter](https://badges.gitter.im/PerfectlySoft/Perfect.svg)](https://gitter.im/PerfectlySoft/Perfect?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
