### ISSUE TITLE
Unexpected networking error: 24 'Too many open files'

### ISSUE THREAD

**Issue by wildfiremedia** [PerfectlySoft/Perfect#185]
On Mac OS X, PerfectTemplate exit or server was shutdown once the wrk benchmark run high volume of connection.

Have no problem with Node.js, Nginx and other http framework in swift.
wrk -t1 -c1000 -d5s http://127.0.0.1:8181/index.html

**Comment by kjessup** [comment]
Corrected. Thank you.
