### ISSUE TITLE
PerfectNet integer type issues

### ISSUE THREAD

**Issue by iamcam** [PerfectlySoft/Perfect#189]
* Building Perfect via SPM
* Debian 8.5 (jessie)
* Beaglebone Black (armv7 / 32bit )
* Swift version 3.0-dev (June 9, 2015)(LLVM eb140647a6, Clang 188b5bf5e2, Swift df68c08020)
Target: armv7--linux-gnueabihf

In addition to build errors reported on the Ubuntu (#187), there are two additional ones that pop up on the Beaglebone Black, a 32bit device.

```
debian@beaglebone:~/Development/delete/Perfect$ swift build
Compile Swift Module 'PerfectNet' (5 sources)
/home/debian/Development/delete/Perfect/Packages/PerfectNet-0.8.0/Sources/NetTCP.swift:26:26: error: integer literal '4294967295' overflows when stored into 'Int'
let INADDR_NONE = UInt32(0xffffffff)
```
and
```
/home/debian/Development/delete/Perfect/Packages/PerfectNet-0.8.0/Sources/NetTCPSSL.swift:234:42: error: cannot convert value of type 'UInt' to expected argument type 'Int'
                SSL_CTX_ctrl(sslCtx, SSL_CTRL_OPTIONS, SSL_OP_ALL, nil)
                                                       ^~~~~~~~~~
                                                       Int(      )
```

**Comment by rymcol** [comment]
Currently Swift is only officially supporting Ubuntu (14.04 & 15.10)

You're probably not going to be able to get that stable until Apple expands support.

**Comment by rymcol** [comment]
Additionally, while some work has been done for arm, I also don't believe they're supporting armv7 / 32bit at all

**Comment by iamcam** [comment]
The Swift on ARM group (which I participate in) is focusing almost solely on armv7 / 32bit for now. This is because a large number of boards are running that architecture. Armv8 simply doesn't compile most of the time, and even with compiled binaries there are plenty issues that prevent it from working. As for OS, I don't know that there's significant difference between Debian and Ubuntu to make a difference (for Perfect).

Fixing these types of issues is probably a good idea, anyway, regardless the architecture.

**Comment by rymcol** [comment]
arm7 support, and really anything that branches out, is very exciting. 

Your code suggests the compiler isn't recognizing the unsigned int and is instead trying to stuff it into a regular int, which in your case is 32 bit, which is why it's giving the error. I can't see any way that can be patched inside of Perfect. It would need to be patched on the language side for the arm7 build of Swift.

**Comment by iamcam** [comment]
I have an update. Thanks to @uraimo -  he pointed out that the statement should be 
```
let INADDR_NONE = UInt32(0xffffffff as UInt32)
```

because  the `0xff` statement is an alias for Int on both armv7 as well as x86_64 systems. It seems the Int init() method is a bit obtuse to this fact, IMO.

**Comment by uraimo** [comment]
Or alternatively, this forces the specific init: `let INADDR_NONE = UInt32(integerLiteral: 0xffffffff)`.

**Comment by iamjono** [comment]
Hi all, can I suggest that you fork the repo needed, make the changes and verify all is working correctly, and then once it's all settled in that you submit a pull request?
For now, closing issue - however it would be great if you could drop into the PerfectlySoft Gitter room for discussion so we can help in that way if we are able!
[![Gitter](https://badges.gitter.im/PerfectlySoft/Perfect.svg)](https://gitter.im/PerfectlySoft/Perfect?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by iamcam** [comment]
I have a fix in a branch but ran into other compile issues related to some recent swift3 changes. I'll take another look today and submit a PR

**Comment by iamcam** [comment]
Submitted https://github.com/PerfectlySoft/Perfect-Net/pull/2
