### ISSUE TITLE
Raspberry pi support?

### ISSUE THREAD

**Issue by dvdblk** [PerfectlySoft/Perfect#191]
Is it possible to use Perfect with Pi?

**Comment by taplin** [comment]
I've seen some of the progress in getting Swift on ARM, but to my knowledge, Perfect has not been tested against that deployment. I saw someone was having some success, at least made it far enough to report some bugs, installing on a Backbone device using Swift on ARM.

**Comment by iamcam** [comment]
@dvdblk I've been looking into Perfect on ARM devices. Last I attempted a few days ago, there was an issue (#189) with some Integer types in Perfect-Net.

Raspberry Pi2 and Beaglebone Black are both armv7 devices, which are "supported" to some degree (compiler, Foundation, Package Manager work; repl is broken, tests are ignored)
Raspberry Pi3 (armv8) is not well supported for now, but you can do some things with it. Last I tried SPM had some issues. 

At this point, Swift on armv7 devices should be good enough to work with Perfect and other similar projects.

If you need more information, you can check out [Joe Bell's post](http://dev.iachieved.it/iachievedit/swift-for-arm-systems/) about Swift 3 on ARM.

**Comment by dvdblk** [comment]
Thank you very much for a clear and useful response. :+1:
