### ISSUE TITLE
It can be made into a simple chat server?

### ISSUE THREAD

**Issue by sonwa** [PerfectlySoft/Perfect#196]
Hi,Perfect have Chat server examples or TCP Multi-connection server examples?

**Comment by iamjono** [comment]
Yes it's 100% suited to working as a chat server - the most recent that was done was a websockets version.

I will see if we are ok to publish that. Will leave the thread open for now and update soon.

**Comment by sonwa** [comment]
websocket use HTTP do? But I do not want HTTP, I would like TCP simultaneous multiple client connections, how to get this?

 Please enlighten me.

**Comment by iamjono** [comment]
You might need to leverage a lower level TCP connection to do this. There's a web sockets example repo if that helps?
https://github.com/PerfectlySoft/Perfect-WebSockets
