### ISSUE TITLE
Swift compiler error

### ISSUE THREAD

**Issue by mtso** [PerfectlySoft/Perfect#202]
Hello Perfect team,
I tried following the README Quick Start instructions.

After I enter the following in Terminal:
`git clone https://github.com/PerfectlySoft/PerfectTemplate.git`
`cd PerfectTemplate`
`swift build`

I get:
`/Users/matthewtso/git/PerfectTemplate/Packages/PerfectThread-0.10.0/Sources/ThreadQueue.swift:210:97: error: cannot convert value of type 'UnsafeMutablePointer<Void>' (aka 'UnsafeMutablePointer<()>') to expected argument type 'UnsafeMutablePointer<_>'`

`/Users/matthewtso/git/PerfectTemplate/Packages/PerfectThread-0.10.0/Sources/ThreadQueue.swift:233:37: error: value of type 'Unmanaged<IsThisRequired>' has no member 'toOpaque'`

`error: exit(1): /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/matthewtso/git/PerfectTemplate/.build/debug.yaml`

Checking my Swift version returns the following:
`Apple Swift version 3.0 (swiftlang-800.0.30 clang-800.0.24)`
`Target: x86_64-apple-macosx10.9`

I'm pretty new and not sure how to diagnose this, is there something I can try to fix this?
Thanks!

**Comment by CharlesHarroch** [comment]
For fix this error, you can use swiftenv
`swiftenv local 3.0`

Or you can create .swift-version file with 3.0

**Comment by mtso** [comment]
Hi, thanks for responding. I am getting these errors with Swift version 3.0. Is there a particular snapshot I should be using?

**Comment by kjessup** [comment]
We will always note the proper snapshot to use on the main README:

https://github.com/PerfectlySoft/Perfect/blob/master/README.md

As of right this moment, we are on DEVELOPMENT-SNAPSHOT-2016-06-20-a

Once the full 3.0 is released we will tag all of our components as 2.0.0.

**Comment by mtso** [comment]
With a fresh clone of PerfectTemplate.git and my local swiftenv set to DEVELOPMENT-SNAPSHOT-2016-06-20-a, I am still running into the compiler errors I posted above when running `swift build`.

**Comment by kjessup** [comment]
Did you:
```
swift build --clean=dist
swift build
```

The dist flag will have it delete all the downloaded packages and re-download the latest versions. This is often necessary when things are changing frequently as they are now.

**Comment by mtso** [comment]
Thanks for the suggestion! Just tried it, but it didn't fix the compiler error.

Where can I find documentation on using Swift's command line tools? I can't seem to find info on the build command and its options in the man pages, and I don't see the `--clean=dist` option when invoking `swift -help build`.

**Comment by CharlesHarroch** [comment]
After update my Perfect package, I've the same error.

**Comment by iamjono** [comment]
@mtso and @CharlesHarroch can you clarify what OS you're using please?

**Comment by iamjono** [comment]
Can you also paste in the output of ```swift --version``` please.
You should get something like this
```$ swift --version
Apple Swift version 3.0-dev (LLVM cb08d1dbbd, Clang 383859a9c4, Swift 9e8266aaeb)
Target: x86_64-apple-macosx10.9```

**Comment by kjessup** [comment]
If you are OS X ensure you have done this step:

https://camo.githubusercontent.com/e2cbfcd5b784b0489653bf2bbf756b4693d369b3/687474703a2f2f7777772e706572666563742e6f72672f646f63732f6173736574732f78636f64655f70726566732e706e67

**Comment by iamjono** [comment]
I just verified on mine and it builds ok, the choosing of the command line tools version is the only thing that might be different.

**Comment by CharlesHarroch** [comment]
I use OS X 10.11.5

`swift --version`
`Apple Swift version 3.0-dev (LLVM c191431197, Clang c6195325c5, Swift add621a959)
Target: x86_64-apple-macosx10.9`

My error :

```
Compile Swift Module 'PerfectThread' (2 sources)
****/Packages/PerfectThread-0.10.0/Sources/ThreadQueue.swift:210:97: error: cannot convert value of type 'UnsafeMutablePointer<Void>' (aka 'UnsafeMutablePointer<()>') to expected argument type 'UnsafeMutablePointer<_>'
            let unleakyObject = Unmanaged<IsThisRequired>.fromOpaque(UnsafeMutablePointer<Void>(p)).takeRetainedValue()
                                                                                                ^
****/Packages/PerfectThread-0.10.0/Sources/ThreadQueue.swift:233:37: error: value of type 'Unmanaged<IsThisRequired>' has no member 'toOpaque'
        let leakyObject = Unmanaged.passRetained(holderObject).toOpaque()
                          ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~
<unknown>:0: error: build had 1 command failures

```

**Comment by mtso** [comment]
I am also using macOS 10.11.5.
Xcode Version 8.0 beta (8S128d)

@kjessup yes, I made sure to set Xcode 8 in Locations > Command Line Tools.

If I package generate an Xcode project, those errors are caught by the checker.

<img width="868" alt="screen shot 2016-06-28 at 10 58 03 am" src="https://cloud.githubusercontent.com/assets/8432061/16426803/6aa66414-3d1f-11e6-8315-48e97982f242.png">
<img width="868" alt="screen shot 2016-06-28 at 11 00 33 am" src="https://cloud.githubusercontent.com/assets/8432061/16426847/9a981424-3d1f-11e6-8d89-f6ea9319bc40.png">

**Comment by iamjono** [comment]
Good news... I've managed to reproduce the error. We'll be back to you soon :)
Thanks!

**Comment by iamjono** [comment]
Solved:
1. Make sure you have the latest (as of current time) snapshot installed. If you have swiftenv installed you can install it using this:
`swiftenv install DEVELOPMENT-SNAPSHOT-2016-06-20-a`
Then select as current using:
`swiftenv local DEVELOPMENT-SNAPSHOT-2016-06-20-a `

2. In Xcode > Preferences > Locations, make sure the Xcode 8 is definitely set for command line tools.
3. Xcode -> Toolchains -> Select the dev snapshot that you just installed.

Then try build.
These steps worked for me, lets hope it solves for you. Please let me know?

**Comment by kurtbitner** [comment]
Hello, I followed your steps above to compile PerfectLib. However, when I try to compile PerfectServer I'm getting this error:
main_fcgi.swift:61:22: error: use of unresolved identifier 'FastCGIServer'
        let fastCgiServer = FastCGIServer()

**Comment by mtso** [comment]
Thank you so much for the help, I really appreciate it. Following the above steps, I'm able to properly compile with `git clone https://github.com/PerfectlySoft/Perfect.git`.

However, I get the same error when I try using the starter project `git clone https://github.com/PerfectlySoft/PerfectTemplate.git`.

In case the bit in the parens might help, my System Version: OS X 10.11.5 (15F34)
And my full terminal output:
[mtso_terminaloutput_062816.txt](https://github.com/PerfectlySoft/Perfect/files/338243/mtso_terminaloutput_062816.txt)

**Comment by CharlesHarroch** [comment]
Same for me

**Comment by colourful987** [comment]
@mtso  whether you change Xcode -> Toolchains -> Swift Development Snapshot 2016-06-20-a? 
@iamjono Thank you for your help. It works for me!

**Comment by tomisacat** [comment]
Do as same as comment said: 
```
1. install DEVELOPMENT-SNAPSHOT-2016-06-20-a;
2. swiftenv local DEVELOPMENT-SNAPSHOT-2016-06-20-a;
3. Xcode -> Preference -> Locations and select Xcode 8;
4. Xcode -> Toolchains -> DEVELOPMENT-SNAPSHOT-2016-06-20-a;
5. clean and build;
```
and my system is `macOS 10.11.5`, but sadly it still got the same error.

**Comment by colourful987** [comment]
@tomisacat try Xcode -> Preference -> DEVELOPMENT-SNAPSHOT-2016-06-20-a

**Comment by colourful987** [comment]
most of people follow the tutorial :
1.  clone PerfectTemplate and  `swift build` , **It works!**
2.  Enter `swift package generate-xcodeproj` in terminal and Open the generated file "PerfectTemplate.xcodeproj" by Xcode IDE ,Ensure that you have selected the executable target and selected it to run on "My Mac" ,**It failed!**

-------------
Solved:
1. install DEVELOPMENT-SNAPSHOT-2016-06-20-a(the lastest),You could download in [swift.org](https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a/swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-osx.pkg),or install [swiftenv](https://github.com/kylef/swiftenv) firstly,then enter `swiftenv install DEVELOPMENT-SNAPSHOT-2016-06-20-a `
2. swiftenv local DEVELOPMENT-SNAPSHOT-2016-06-20-a;
3. Xcode -> Preference -> DEVELOPMENT-SNAPSHOT-2016-06-20-a(Not Xcode 8);
4. Xcode -> Toolchains -> DEVELOPMENT-SNAPSHOT-2016-06-20-a;
5. clean and build;

Hope this could help you

**Comment by tomisacat** [comment]
@colourful987 Thanks for helping. But What do you mean about `3. Xcode -> Preference -> DEVELOPMENT-SNAPSHOT-2016-06-20-a(Not Xcode 8)`? I could only find Command Line Tools(and select Xcode 8) in `Location` tab and Toolchains(Swift Development Snapshot selected) in `Component` tab.

btw, only these Swift versions installed in my system:
```
$> swiftenv version
* DEVELOPMENT-SNAPSHOT-2016-06-20-a (set by /Users/my_user_name/WorkSpace/PerfectTemplate/.swift-version)
  3.0
  2.1.1
```
and as you see, the development snapshot is the current version for the project.

**Comment by tomisacat** [comment]
It just worked strangely that I re-clean-and-build and I checked the last commit, it's early than the time I tried last time. Strange but amazing : )

**Comment by FibonacciRedstone** [comment]
@colourful987 I have been attempting to get my project working. I tried cloning the PerfectTemplate and running swift build.....And I got the same error as with my own project. I have the newest snapshot downloaded and have it selected however I still get the error.

**Comment by iamjono** [comment]
@FibonacciRedstone i presume you have followed the steps @colourful987 laid out? 

> Solved:
> 1. install DEVELOPMENT-SNAPSHOT-2016-06-20-a(the lastest),You could download in swift.org,or install swiftenv firstly,then enter swiftenv install DEVELOPMENT-SNAPSHOT-2016-06-20-a
> 2. swiftenv local DEVELOPMENT-SNAPSHOT-2016-06-20-a;
> 3. Xcode -> Preference -> Components->DEVELOPMENT-SNAPSHOT-2016-06-20-a(Not Xcode 8.0);
> Or Xcode -> Toolchains -> DEVELOPMENT-SNAPSHOT-2016-06-20-a;
> 5. Xcode -> Location -> Command Line Tools -> Xode8
> 6. clean and build;

**Comment by FibonacciRedstone** [comment]
@iamjono I don't have "swiftenv" installed however I have installed the 6-20 snapshot and my swift --version shows this. I also have steps 3-6 completed and I am still getting those errors

**Comment by mtso** [comment]
I figured out what went wrong on my end.
Didn't realize I had to make the tools available for use in my Terminal by running the following in my Terminal:
`$ export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"`
Now PerfectTemplate also builds without error.
Thanks, all!
