### ISSUE TITLE
Missing OpenSSL

### ISSUE THREAD

**Issue by kurtbitner** [PerfectlySoft/Perfect#203]
Hello,

I built the latest version of PerfectLib with the correct Swift snapshot. However, when I import the .xcodeproj or a compiled version of the framework into Xcode whenever I try to compile my program the compiler says "Missing required module 'OpenSSL'." Also, I ran 'brew link openssl --force' to force symlink the openssl libs to /usr/local/include/openssl.

Thanks!

**Comment by iamjono** [comment]
Hi @kurtbitner - are you trying to use Perfect 1 or the latest (which is v2)
The best way to get v2 running is to use the Swift Package Manager as outlined here: https://github.com/PerfectlySoft/Perfect-MongoDB#quick-start

We'll be updating some of our docs soon to reflect this specifically (plus, a whole new docs package!)

**Comment by kurtbitner** [comment]
I'm using Perfect 2

**Comment by jarrydfillmore** [comment]
+1!

**Comment by iamjono** [comment]
Does it still build anyway?

**Comment by Lidbetter** [comment]
I believe this has something to do with [module.modulemap](https://github.com/PerfectlySoft/Perfect-OpenSSL/blob/0.3.0/module.modulemap) definition in the [Perfect-OpenSSL](https://github.com/PerfectlySoft/Perfect-OpenSSL/tree/0.3.0) wrapper and some xcode caching.

With a plain project (created by making the Package file then running `swift package generate-xcodeproj` see screenshot)
![screen shot 2016-07-03 at 17 54 38](https://cloud.githubusercontent.com/assets/6525616/16547971/d70401bc-414c-11e6-8385-f611da1feacc.png)

using `import PerfectLib` in `Sources/main.swift` works fine, but if you create any other file and try to import PerfectLib the open ssl error is thrown during build.
![screen shot 2016-07-03 at 18 14 28](https://cloud.githubusercontent.com/assets/6525616/16547985/3228d356-414d-11e6-8b5f-a475efaa15bb.png)

changing the [module.modulemap](https://github.com/PerfectlySoft/Perfect-OpenSSL/blob/0.3.0/module.modulemap) to (added [system] to line 1):
```
module OpenSSL [system] {
	header "/usr/local/include/openssl/ssl.h"
	header "/usr/local/include/openssl/err.h"
	header "/usr/local/include/openssl/x509.h"
	header "/usr/local/include/openssl/sha.h"
	header "/usr/local/include/openssl/bio.h"
	link "crypto"
	link "ssl"
	export *
}
```

Seemed to fix the error - the [docs](https://github.com/apple/swift-package-manager/blob/swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a/Documentation/SystemModules.md) have included the word `[system]` for as long as tha doc file has existed.

After locally "fixing"(?) the file once, if I reverted the changes (tried regenerating the xcode project too) I couldn't make it fail again - I suspect caching, but I didn't try too hard to break it again.

see: https://github.com/PerfectlySoft/Perfect-OpenSSL/pull/1

**Comment by Lidbetter** [comment]
Nope, I was wrong - check all your source files have your executable as their target membership

**Comment by radvansky-tomas** [comment]
same for me, openssl is not part of generated xcode project file

**Comment by radvansky-tomas** [comment]
![image](https://cloud.githubusercontent.com/assets/12473664/16666104/79a27930-4486-11e6-8801-f06ea6765fe3.png)

**Comment by taplin** [comment]
make sure your source files have your primary product as a selected Target.


Tim Taplin

**Comment by radvansky-tomas** [comment]
This happen exactly if you follow instructions...i did not change anything...
There is a problem within openssl package

**Comment by taplin** [comment]
I had this exact problem this morning, and after reviewing related emails, checked the file and it had only selected the top Perfect Product, I think it was PerfectThread as a target, and once I selected the module I was building, the OpenSSL error went away.

I don’t know why this issue manifests itself as an OpenSSL error, but it should resolve your problem.

Tim Taplin

**Comment by radvansky-tomas** [comment]
that may help you, but as I said...openssl library is not part of generated project, whole openssl directory is missing in dependency folder. There is no sign of openssl in xcode project! Changing of target does not change much on this fact :(

**Comment by kjessup** [comment]
The OpenSSL package is a C module and so has no source code and will not appear in the Dependencies group.

On the command line, please try the following:

```swift build --clean=dist```
```swift build```

If it builds successfully, regenerate the Xcode project:

```swift package generate-xcodeproj```

And of course if it does not build then please report back with the output you get on the command line.

**Comment by radvansky-tomas** [comment]
cmd build works thats not a problem, only xcode cannnot find openssl. 

Odoslané z iPhonu

Dňa 7. 7. 2016, o 21:58, Kyle Jessup <notifications@github.com> napísal:

**Comment by radvansky-tomas** [comment]
Ok GOT IT, for others: Make sure that your path does not contains any white space !!! xcode translated white space to separate entries in definition for header paths -> and therefore it cant find openssl
