### ISSUE TITLE
Sample Access the server’s document directory and return an image file to the client occurred Problem

### ISSUE THREAD

**Issue by colourful987** [PerfectlySoft/Perfect#206]
**Codes:**
```
Routing.Routes["/pic"] = {
  request, response in
  let docRoot = request.documentRoot
  let path = "~/Desktop/Server-Side-Swift/day03-perfect/PerfectTemplate/webroot/mr_pebbles.jpg"
  do{
    let mrPebbles = File(path)
    let imageSize = mrPebbles.size
    let imageBytes = try mrPebbles.readSomeBytes(count: imageSize)
    response.setHeader(.contentType, value: MimeType.forExtension("jpg"))
    response.setHeader(.contentLength, value: "\(imageBytes.count)")
    response.appendBody(bytes: imageBytes)
  } catch {
    response.status = .internalServerError
    response.appendBody(string: "Error handling request : \(error)")
  }
  response.completed()
}
```

**Error Descripton:** Error handling request : fileError(2, "No such file or directory /Users/pmst/Desktop/Server-Side-Swift/day03-perfect/PerfectTemplate/Packages/PerfectLib-0.42.0/Sources/PerfectLib/File.swift open 164")

**Comment by colourful987** [comment]
I found mrPrbbles.exists value is false. However It exists and path is correct.

**Comment by colourful987** [comment]
Solved:
Ensuring path is **absolute** Path, relative path doesn't seem to work.

**Comment by colourful987** [comment]
File.swift Line 54
```
return access(internalPath, F_OK) != -1
```

whether access function in unistd module support relative path ?

**Comment by colourful987** [comment]
I'm sorry I was so careless.
`access` function supports relative path. However, Using Xcode IDE is different from command line **(webroot path and executable file)!** 
* path1 using Xcode : `~/Library/Developer/Xcode/DerivedData/PerfectTemplate-cayyrjbwngppuagfepkntzatlxzo/Build/Products/Debug/webroot/mr_pebbles.jpg`
* path2 using command line: `your project/webroot/mr_pebbles.jpg` 

I forget to put picture in path1 rather than path2, so it could not find it.

**Comment by kjessup** [comment]
I just added support for expanding tildes in paths. What you are doing should work now. The tilde will be replaced with the path to the current user's home directory.

Make sure you ```swift build --clean=dist ; swift build``` and regenerate the Xcode project.
