### ISSUE TITLE
Run Perfect on DigitalOcean server 

### ISSUE THREAD

**Issue by cooler333** [PerfectlySoft/Perfect#208]
Needs template or tutorial for DigitalOcean.

now i get next log to console. But how can i get link to server?  

    root@CoolServerFactory:~/PerfectTemplate# swift build
    Compile Swift Module 'PerfectThread' (2 sources)
    Compile Swift Module 'PerfectNet' (5 sources)
    Compile Swift Module 'PerfectLib' (11 sources)
    Compile Swift Module 'PerfectHTTP' (9 sources)
    Compile Swift Module 'PerfectHTTPServer' (5 sources)
    Compile Swift Module 'PerfectTemplate' (2 sources)
    Linking .build/debug/PerfectTemplate
    root@CoolServerFactory:~/PerfectTemplate# .build/debug/PerfectTemplate
    [INFO] Starting HTTP server on 0.0.0.0:8181 with document root ./webroot
        // exit
    ^C

**Comment by cooler333** [comment]
same issue in other projects:

    root@CoolServerFactory:~/PerfectExamples/PerfectExample-UploadEnumerator# .build/debug/UploadEnumerator
    [INFO] Starting HTTP server on 0.0.0.0:8181 with document root ./webroot

and then i get: This site can’t be reached

how to start server on DigitalOcean instead of start local server inside DO droplet?

**Comment by rymcol** [comment]
0.0.0.0 is a local IP - you would have to set this to the public IP assigned to the server by DigitalOcean in order to reach the site. 

You can do this with: 

`server.serverAddress = "123.456.789.000"` in main.swift where you replace the IP with yours, assuming you're using the current or very recent master branch.

**Comment by cooler333** [comment]
yyyyyes!) Thank you, i've got already do this ins the same way) and fix port. and it's worked!
