### ISSUE TITLE
No such module 'OpenSSL'

### ISSUE THREAD

**Issue by mnbao1975** [PerfectlySoft/Perfect#209]
Dear Perfect Team,

I did use the Swift Package Manager to generate an Xcode project, but when I build this project on Xcode, I got the error of "No such module OpenSSL". I also did use brew to install openssl on my Mac. See attached file for more info.

Regards,
Bao
![2016-07-16_23-15-12](https://cloud.githubusercontent.com/assets/4511577/16895850/a54d6956-4bab-11e6-8868-d5c2e818c337.png)

**Comment by iamjono** [comment]
Hi @mnbao1975 did you also force the linkages?

`brew link openssl --force`

**Comment by mnbao1975** [comment]
Yes, I did that. 


Thanks,
Bao

**Comment by colourful987** [comment]
![img](https://cloud.githubusercontent.com/assets/4601666/16980434/813993a6-4e98-11e6-8ea5-fbaa966a086f.PNG)
Try to change **"Xcode Practics"**  filename to **"Xcode-Practics"**。NO Blank Character

**Comment by mnbao1975** [comment]
Yeah! That works. Many thanks Chao Ma.

Bao
