### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by nvh** [PerfectlySoft/Perfect#21]
After [this](https://twitter.com/nvh/status/670320301566205953) I feel obliged to share some of the process here. Ideally I would like to turn this into a pull request, but as my hacking isn't really ready for merging yet, I'll just share the steps I remember here, so the thinking doesn't have to be performed twice :)

- [ ] Copied OSX target and changed the SDK to tvOS
- [ ] Added `import Foundation` to some files
- [ ] Removed `SysProcess` from the tvOS target
- [ ] Built custom tvOS versions of libcurl.a libssl.a and lib crypto.a using [this](https://github.com/jasonacox/Build-OpenSSL-cURL)
- [ ] Built custom version of libevent using [this](https://gist.github.com/nvh/9b8c60b41df7c665c900) (I'm not really sure of the removal of fork in this case, but as it's only in tests, it should be okay)
- [ ] Replaced the other libraries (libicu and libsqlite) with the tvOS versions provided by Apple

A problem that I haven't solved yet, but shouldn't be hard is that the creation of the session database currently fails, because it uses a file it can't access. This is also a theoretical problem: As we are only allowed to store cache on appleTV, does in matter if the session database gets wiped every time the app quits? Probably not, depending on your use case.

I hope I covered everything. As I said, I will try and fix this up in a PR soon!

**Comment by igor9silva** [comment]
+1 for official AppleTV support. Would like to help.

**Comment by jhoughjr** [comment]
I could really use this, wouldn't mind helping, though my ObjC legs are sturdier than my Swift wings currently.

**Comment by iamjono** [comment]
Hi Niels - Closing the issue for now although I can't see a PR from you on this. If you did manage to make some further progress on it, please let us know. Note that there's been a significant movement forward since December '15! Thanks!
