### ISSUE TITLE
Autocompletion doesn't work with Xcode 8

### ISSUE THREAD

**Issue by cooler333** [PerfectlySoft/Perfect#213]
I'm using snapshot(16.06.20) version of swift via toolchain in Xcode 8.

I have some code syntax highlighting, but can't use "command+mouse left click" (go to declaration), "alt+mouse left click" have same behaviour ("No Quick Help").

Have I write all code by the hand? Without autocompletion?

Project compiles (console output):

```
[INFO] Starting HTTP server on 0.0.0.0:8181 with document root ./webroot
```

And also run successful on DigitalOcean server(host).

**Comment by Lidbetter** [comment]
Sounds like an xcode bug.

Close the xcode window, then quit xcode - it will probably work when you restart it.

If it doesn't, check activity monitor for xcode related services (my sourcekit on xcode 8 leaks memory) and quit those (then restart xcode again)

**Comment by rymcol** [comment]
You may have to build at least once before it can autocomplete as well
