### ISSUE TITLE
Send data with POST / GET request

### ISSUE THREAD

**Issue by tuyenbq** [PerfectlySoft/Perfect#24]
Hi,
First, thank you so much for your awesome framework.
Please help to explain how could i send data with POST / GET request from client and how to receive those params on server via Swift code ?
Many thanks for your help.

**Comment by Ankish** [comment]
Its clear the code. Please check - Client / Server project.

**Comment by tuyenbq** [comment]
oh yes, i got it. Tks!

**Comment by tranhieutt** [comment]
For example, you can ref,very clear:
	func buttonPressed(Sender: AnyObject) {
		if let loc = self.selectedLocation {
			
			let lat = loc.coordinate.latitude
			let long = loc.coordinate.longitude
			
			let postBody = "lat=\(lat)&long=\(long)"
			
			let req = NSMutableURLRequest(URL: NSURL(string: END_POINT)!)
			req.HTTPMethod = "POST"
			req.HTTPBody = postBody.dataUsingEncoding(NSUTF8StringEncoding)
			
			let session = NSURLSession.sharedSession()
			
			let task = session.dataTaskWithRequest(req, completionHandler: {
				(d:NSData?, res:NSURLResponse?, e:NSError?) -> Void in
				if let _ = e {
					print("Request failed with error \(e!)")
				} else {
					
					let strData =  String(data: d!, encoding: NSUTF8StringEncoding)
					print("Request succeeded with data \(strData)")
					do {
						if let strOk = strData {
							let jsonDecoded = try JSONDecode().decode(strOk)
							if let jsonMap = jsonDecoded as? JSONDictionaryType {
								
								if let sets = jsonMap.dictionary["resultSets"] as? JSONArrayType {
									// just one result in this app
									if let result = sets.array.first as? JSONDictionaryType {
										if let timeStr = result.dictionary["time"] as? String,
											let lat = result.dictionary["lat"] as? Double,
											let long = result.dictionary["long"] as? Double {
											
												self.timeStr = timeStr
												self.lat = lat
												self.long = long
												
												dispatch_async(dispatch_get_main_queue()) {
													self.performSegueWithIdentifier("showMap", sender: self)
												}
										}
									}
								}
							}
						}
					} catch let ex {
						print("JSON decoding failed with exception \(ex)")
					}
				}
			})
			
			task.resume()
			
		} else {
			// no location
			
			let alert = UIAlertController(title: "No Location", message: "Ensure that location services are available and try again.", preferredStyle: .Alert)
			let action = UIAlertAction(title: "OK", style: .Default) {
				(a:UIAlertAction) -> Void in
			}
			alert.addAction(action)
			self.presentViewController(alert, animated: true) { }
		}
	}

**Comment by tuyenbq** [comment]
thank you, thank you and thank you so much guy. (y)

**Comment by Tomikes** [comment]
I want an example to use the library to do the web background, it is best to have a picture of the kind!
help me。。

**Comment by iamjono** [comment]
Closing the issue as it's been addressed.
However @Tomikes if you're still having issues could you open a new issue with some specifics and some code samples you're having problems with. Thanks!
