### ISSUE TITLE
Swift is now open source

### ISSUE THREAD

**Issue by kylefrost** [PerfectlySoft/Perfect#25]
Finally open source!
Can't wait to use this project on my Linux server.

[Swift website.](https://swift.org/)

**Comment by cielpy** [comment]
The website is too slow...

**Comment by vittoriom** [comment]
http://cjwirth.com/swift-org/

**Comment by kylefrost** [comment]
Source is up on @apple's GitHub.

**Comment by honghaoz** [comment]
Hello! Linux version!

**Comment by levin-ilya** [comment]
\o/

**Comment by HarshitDaftary** [comment]
Can't download  library from this link

http://cjwirth.com/swift-org/builds/ubuntu1510/swift-2.2-SNAPSHOT-2015-12-01-b/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu15.10.tar.gz

**Comment by gildo** [comment]
@HarshitDaftary https://swift.org/download/

**Comment by HarshitDaftary** [comment]
It worked, Thanks @gildo

**Comment by KeithMorning** [comment]
When will we can get a version for Linux? Thanks, can't wait for it.(smaile)
