### ISSUE TITLE
Perfect Assistant Deploy to Ec2 Problem

### ISSUE THREAD

**Issue by hulk10425** [PerfectlySoft/Perfect#251]
I want to deploy the "PerfectAppTemplate" to aws ec2, but face an problem.

In final ec2 setting that is a field of Key pair, but I just can't chose any key pair.

someone can tell me why?

I think maybe I should put the xxx.pem file into some specific folder.

image is here https://imgur.com/a/cDjZ8JG  

thank you !

**Comment by saroar** [comment]
did you check this tutorial?
https://perfect.org/en/assistant/deployment-ec2.html
https://medium.com/server-side-swift-and-more/deploying-server-side-swift-on-aws-9949a241a45a

**Comment by hulk10425** [comment]
yes, I have watched both articles and  follow those steps, but just stuck on the last step about deployment.  Just like the image url showed.

**Comment by hulk10425** [comment]
I just find the answer. It's works on Xcode 9.2 but somehow don't work on Xcode 9.3.
