### ISSUE TITLE
Why theading not work

### ISSUE THREAD

**Issue by fisherjoe** [PerfectlySoft/Perfect#256]
When I use Theading as follow. My expected printed message is 『Do something first!』『After do something!』，but the result runing is opposite. Is there anything wrong about Threading ? And How could I perform in main thread?

func handler(request: HTTPRequest, response: HTTPResponse) {

    let event = Threading.Event()
    Threading.dispatch {
        Threading.sleep(seconds: 3)
        print("Do something first!")
        event.signal()
    }

    _ = event.wait()
    print("After do something!")
    
	// Respond with a simple message.
	response.setHeader(.contentType, value: "text/html")
	response.appendBody(string: "<html><title>Hello, world!</title><body>Hello, world!</body></html>")
	// Ensure that response.completed() is called when your processing is done.
	response.completed()
}

**Comment by kjessup** [comment]
You have to call `.lock()` before calling signal or wait, followed by `.unlock()`.
It's described more in this document:
https://www.perfect.org/docs/thread.html

**Comment by fisherjoe** [comment]
@kjessup I have try adding lock to it , but it is also not working.
