### ISSUE TITLE
couldn't connect to websocket server 

### ISSUE THREAD

**Issue by Su-Huanzhen** [PerfectlySoft/Perfect#263]
I developed an IOS WebSocket client  using 
self.socket = WebSocket(url:URL(string: "ws://localhost:8181/echo")!)
but couldn't connect to the WebSocket server, but I can connect to other WebSocket server

**Comment by saroar** [comment]
check if you need protocol something like this `let socket = WebSocket(url: URL(string: "ws://localhost:8181/api/v1/chat")!, protocols: ["chat"])`

**Comment by Su-Huanzhen** [comment]
my bug is occurred because of our perfect-websocket-server ,it is none business of the webscoket-client

**Comment by Su-Huanzhen** [comment]
I tried, once I connect to the perfect WebSocket  server ,the error info as below:
error:Optional(Starscream.WSError(type: Starscream.ErrorType.upgradeError, message: "Invalid HTTP upgrade", code: 400))

**Comment by saroar** [comment]
may be check my code https://github.com/saroar/RealtTimeChatWithAppPerfectWebSocketApi and `Starscream` pod version

**Comment by Su-Huanzhen** [comment]
Hi my guy,Thank you ,      
the WebSocket-client should be this :
self.socket = WebSocket(url: URL(string: "ws://localhost:8181/echo")!,protocols: ["echo"])

not like this:
self.socket = WebSocket(url: URL(string: "ws://localhost:8181/echo")!)
