### ISSUE TITLE
Date type in PostgresStORM parseRows function crash, when it is null

### ISSUE THREAD

**Issue by 0xfeedface1993** [PerfectlySoft/Perfect#278]
I have a PostgresStORM subclass called 'PPlayer' have "birthday" with date type in datebase, program crash on 'parseRows' function:

```
let output = result.getFieldString(tupleIndex: x, fieldIndex: f)
let formatter = DateFormatter()
formatter.dateFormat = "yyyy/MM/dd hh:mm Z"

// CRASH HERE
params[result.fieldName(index: f)!] = formatter.date(from: output!)
```

** Output is null or nil in here**, that crash everything.

It's mean we should design datebase for date type with non-null field or bug?

**Comment by kjessup** [comment]
I've submitted a fix for this to get rid of the force unwrapping.
It's tagged as 3.2.1.
