### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by xissburg** [PerfectlySoft/Perfect#289]
The last commit was 3 months ago and I haven't seen much recent activity. ~~I am unable to join the Slack channel~~.  So is this project basically dead?

EDIT: I've got to join Slack now after some failed attempts (was getting HTTP 502-504)

I am looking to decide what to use for a backend and thought of server-side Swift (instead of going with some NodeJS thing) and found this but I am quite skeptical.

**Comment by saroar** [comment]
No it last not dead lots people use it check document and slack channel  is active too

**Comment by GJNilsen** [comment]
If you want a more «alive» variant, you should go for Vapor. https://vapor.codes/

**Comment by nlanguage** [comment]
Looking into Perfect for a week and many other language's projects were abandoned, I don't think most of programmers have realized the complexity problems in many libraries.

Why don't we build the **next generation programming language** for the community?

**Comment by GJNilsen** [comment]
I do not think there is room for yet another programming language. Adopting current languages and evolving libraries is the way to go.
There is a plethora of different languages, GO, Erlang, R, Python, Java, JS, PHP and so on, all having its proponents. Making another “standard” language will add just another language to the mix.
The most intriguing language at the moment is Swift, with its new SwiftUI and Combine. A SwiftHTML and a Combine driven server architecture is really enticing I think.
Vapor is the one closest to something like this, and is also having a lot of traction.

**Comment by nlanguage** [comment]
No doubt Swift is fast growing but Vapor web framework doesn't grow beyond the current ecosystems where other languages excel in, still there are tradeoffs (coding complexity, huge memory consumption, etc) in every languages. I have used many programming languages and web frameworks.

The next language could be well-rounder, think differently why **performance and language design matter**.

**Comment by GJNilsen** [comment]
Swift on the server is way faster than nodejs, it consumes a fraction of the memory, and regarding to complexity, its a really simple language. So imho Swift is the most efficient language, since code can be shared between server and clients. Also Swift support for Android is in the works. The most unified language for server, web, mobile and stationary devices is in fact Swift at the moment.

**Comment by nlanguage** [comment]
@GJNilsen Maybe you could have a look at simple benchmark, some language and Nodejs are faster than Swift.
https://github.com/the-benchmarker/web-frameworks

**Comment by GJNilsen** [comment]
I have read the benchmarks, and only some ruby and rust frameworks are faster than swifter, a Swift framework, 8th place btw.

**Comment by nlanguage** [comment]
@GJNilsen Thank for your time reading on the benchmark, we seen these problem if we start using more than one programming language.

Anyway, the idea if the community with experience in writing compilers and interpreters willing to join in their evolutions including from language researchers across universities. They can reach me, nlanguage9@gmail.com

Thanks!

**Comment by GJNilsen** [comment]
Thats why I think that making a new standard language will fail, as with almost all “standards”, every time someone wants to make an industry standard, they end up with just adding one more standard to the big bucket of standards.

A new language is just that, another new language. And without backing of big corporations and key figures in the community, your effort is doomed already before you write your first line of code.

Mark my words, today, August 20th, I told you that your language will fail. In a couple of years I will link to this comment, and say “Told you so”. Unless I have forgotten all about you and your language.

**Comment by saroar** [comment]
@GJNilsen i read lots about Rust I know Swift and i read read it lost of same things in Rust also Rust is very very promising language have my own webpage + API for my ios app with Perfect swift back end but thinking to move RUST :) may you don't recommend me go to rust :) i know also i read VAPOR 3 book its really good :)

**Comment by GJNilsen** [comment]
@saroar Im not saying Rust is crap. If you like and master Rust, well, all the more props to you.

I was just argumenting against "another programming language", pitted from a nobody that just joined github. There are lots of great languages for building amazing stuff, Rust, Go, Swift, you name it, but I do not think there is room for just another "conventional" programming or scripting language thats going to be universal for all types of devices. The last kid to the party is Flutter, but I cant see it will get any major traction for the time being.

**Comment by tanner0101** [comment]
@ghost Vapor 4 is also looking to see a decent performance boost in https://github.com/the-benchmarker/web-frameworks. It's built on Swift NIO 2 and Swift 5 which have lots of great improvements for server-side Swift like UTF-8 native strings.

**Comment by saroar** [comment]
@tanner0101 there only vapor 3.3

**Comment by pman215** [comment]
@tanner0101 as part of the Swift Server Working Group - could you please provide a bit of input on future plans for projects like this which don't have presence on the SSWG? It seems that only members from Apple, Vapor and Kitura are part of the group. 

@kjessup is there anything that can be done to help this project come back to life?

**Comment by proyb6** [comment]
We all heard IBM drops Kitura, another dead project. Vapor is the only popular web framework while other languages has plenty

**Comment by GJNilsen** [comment]
I have not heard that, @proyb6, do you have any links?
There is another framework as well, http://zewo.io/ and it looks really promising.

**Comment by proyb6** [comment]
@GJNilsen It’s on HackerNews
https://news.ycombinator.com/item?id=21808619

**Comment by GJNilsen** [comment]
Its sad to se Kitura go, not because I use it, but competing string libraries drive innovation. Im waiting for Vapor 4 to be released for starting to port a big backend from php.

**Comment by proyb6** [comment]
While I’m in no position to influence any big decisions to port to Vapor 4 or other web frameworks. There’s a big benefit by separating each services to different languages or non-web frameworks route if performance is needed.

**Comment by Jinxiansen** [comment]
@GJNilsen @proyb6 

[Vapor 4.5 version](https://github.com/vapor/vapor/releases) has been released, this may be the last hope of the rise of Swift server.
Look forward to and bless it!

**Comment by proyb6** [comment]
@Jinxiansen What it means by `this may be the last hope of the rise of Swift server`?

**Comment by Jinxiansen** [comment]
@proyb6 

Because `Perfect` has survived and no one maintains it; **IBM ** also gave up` Kitura`; now only `Vapor` is left, I hope it can support this blue sky on the `Server Side Swift`, and hope to get **Apple** ’s in the future Strong support and hope that the future development will get better and better!

Even if one day old I can't write any code, go home and move the bricks.
I will also silently wish in my heart: I hope that `Vapor` will become better and stronger!

Because, I am a big fan of `Vapor` and` Swift`! 💪💪💪

**Comment by proyb6** [comment]
@Jinxiansen The problem some web frameworks solve may be opinionated. The language of cloud computing space has been filled by others e.g. Java, Go, etc, that where everyone knows how to move the bricks like you do.

**Comment by Jinxiansen** [comment]
@proyb6 
Although know that it may not be able to compare with other mature server-side frameworks.
But this is faith. 😔😔

**Comment by sukhrobkhakimov** [comment]
@xissburg @GJNilsen @Jinxiansen You may want to look at my project [Chaqmoq](https://chaqmoq.dev). Although it is very young, it is promising and in a constant development. I didn't want to post this in the issue of another web framework because I thought it was inappropriate. But, since it looks like it is dead, we need alternatives so I decided to inform you that there are other developers apart from SSWG who are also excited about Swift on Server Side and dedicating their time and effort on improving Swift ecosystem. I'd love to get your feedback and contributions on the project.

**Comment by GJNilsen** [comment]
I fins it extremely interesting when new frameworks pop up. Competition drives innovation, so with Vapor as the de facto serverside framework, any competition that keeps them from getting complacent is welcome.
I would love to give it a spin, but I'm drowning in work at the moment. I'll star and watch the project though and keep an eye on it.
Mentioning other frameworks in a community for a completely dead framework is great, you can help others move on. So thanks for mentioning it!
