### ISSUE TITLE
MYSQL / MongoDB Doc

### ISSUE THREAD

**Issue by TheAbstractDev** [PerfectlySoft/Perfect#29]
I frenquently use MYSQL or MongoDB for my websites, APIs and other and I would like to use these with Perfect.. But we haven't docs for these Connectors

**Comment by diejmon** [comment]
+1 I'm trying to use MongoDB Connector but can't link it to my module.

I think the following error:
 error: module 'MongoDB' has no member named ‘MongoClient'

**Comment by generatronServer** [comment]
@TheAbstractDev The best way to go is to check the tests in the connectors.

**Comment by iamjono** [comment]
I've updated the ReadMe on the Perfect-MongoDB repo [(https://github.com/PerfectlySoft/Perfect-MongoDB)](https://github.com/PerfectlySoft/Perfect-MongoDB) to include a "Quick Start" and some sample code.

**Comment by iamjono** [comment]
The MySQL and PGSQL will follow shortly!
