### ISSUE TITLE
AWS / MARIADB Connection issues

### ISSUE THREAD

**Issue by SAPIENTechnologies** [PerfectlySoft/Perfect#298]
I am trying to connect to your technical support but all of your links give a 502 error.

In any case, I am using your MariaDB lib in a macOS app that I am developing. I am trying to connect to an Amazon RDS (MariaDB) instance. I have all of the connection information and I can connect to the DB using Navicat, so I know the connection info is valid.

Using your sample code located here (https://www.perfect.org/docs/MariaDB.html) with my credentials, I try to connect to the db with my app. I always get the following error:

ConnectToServer: connect() failed path:/var/run/mDNSResponder Socket:10 Err:-1 Errno:1 Operation not permitted
Unknown MySQL server host

Any help on this would be appreciated.

**Comment by RockfordWei** [comment]
hi @SAPIENTechnologies , please move this issue to [Perfect-MariaDB](https://github.com/PerfectlySoft/Perfect-MariaDB) home page
