### ISSUE TITLE
Perfect Server runs fine in Xcode, but not when I click the .app file.

### ISSUE THREAD

**Issue by starkshaw** [PerfectlySoft/Perfect#30]
Perfect Server runs fine in Xcode when I click the "run" button, but not when I click the .app file in Finder. How to figure this out?

**Comment by kjessup** [comment]
Find where Xcode spits out the PerfectLib.framework for OS X (ctrl-click in the Products group and choose "Show in Finder"). Make a symlink to that in /Library/Frameworks.

You could copy it into Frameworks, but making a symlink ensures it always up to date on your dev machine.
