### ISSUE TITLE
can't start perfectserverfcgi on Ubuntu 15.10

### ISSUE THREAD

**Issue by groovelab** [PerfectlySoft/Perfect#34]
Running on Ubuntu 15.10(64bit)

I can start ```perfectserverhttp```.
But, I can not start ```perfectserverfcgi```.

https://github.com/PerfectlySoft/Perfect/blob/master/PerfectLib/NetNamedPipe.swift#L82
I catch exception on this line.
```Unexpected networking error: 22 'Invalid argument'```

Thanks

**Comment by nmorenor** [comment]
Hey, 

Seems that I'm running on the same error, also running on Ubuntu 15.10 (64bit) the perfectserverhttp is running but not perfectserverfcgi. I did setup an apache server to use the mod_perfect.o to use the FastCGI. But when I ran the perfectserverfcgi it throws this output.

root@9efc196731c1:/var/www/swift/Examples/Authenticator# ../../PerfectServer/perfectserverfcgi 
Current working directory: /var/www/swift/Examples/Authenticator
perfectserverfcgi: /home/buildslave/jenkins/workspace/oss-swift-linux-packages-ubuntu_15_10-one-off-build/swift/include/swift/Runtime/../../../stdlib/public/SwiftShims/RefCount.h:207: bool StrongRefCount::doDecrementShouldDeallocate() [ClearPinnedFlag = false]: Assertion `newval + quantum >= RC_ONE && "releasing reference with a refcount of zero"' failed.
Aborted

The apache error log have just an entry for the 500 error:

[Mon Dec 14 02:27:31.761860 2015] [watchdog:emerg] [pid 424:tid 140440684291840] (500)Unknown error 500: [client 192.168.99.1:62315] Unable to connect on: /var/www/swift/Examples/Authenticator/Authenticator/../perfect.fastcgi.sock 2 No such file or directory

Cheers

**Comment by DJBen** [comment]
I compiled the Libs and Server on Ubuntu 15.10 (64bit) and run on the Swift 2.0 snapshot released on Dec 10. Both of the perfectserverhttp and perfectserverfcgi dumped with exactly the same message

Current working directory: /home/djben/Documents/Perfect/PerfectServer
perfectserverhttp: /home/buildslave/jenkins/workspace/oss-swift-linux-packages-ubuntu_15_10/swift/include/swift/Runtime/../../../stdlib/public/SwiftShims/RefCount.h:207: bool StrongRefCount::doDecrementShouldDeallocate() [ClearPinnedFlag = false]: Assertion `newval + quantum >= RC_ONE && "releasing reference with a refcount of zero"' failed.
Aborted (core dumped)

Does the current working directory matter? How did you manage to get the http work? Thanks.

**Comment by kjessup** [comment]
Acknowledging the crash. Trying to track it down now.

Thanks
