### ISSUE TITLE
Permissive license - ASL 2.0, MIT, BSD

### ISSUE THREAD

**Issue by sirinath** [PerfectlySoft/Perfect#35]
Can you consider moving to a permissive license?

**Comment by C0deH4cker** [comment]
There's already some discussion about potentially changing or modifying the license to be more permissive in issue #26

**Comment by SeanStephens** [comment]
Thanks for the feedback, it was helpful. We've switched to Apache, and your request was part of this decision. Happy coding!

https://github.com/PerfectlySoft/Perfect/issues/131
