### ISSUE TITLE
Issue when launching the server on Ubuntu 15-10 : "the file / was not found"

### ISSUE THREAD

**Issue by Khalil-Ciret** [PerfectlySoft/Perfect#36]
Hello,

I have a problem when i launch the perfectserverhttp from Ubuntu 15-10.
![capture d ecran 2015-12-14 a 17 59 00](https://cloud.githubusercontent.com/assets/14749617/11787575/af163b3e-a28c-11e5-8d82-75b59e8efc1d.png)

The server launches properly, but then i can't manage to work with it. The message "The file "/" was not found" is displaying on the navigator.

Could it be because i use a virtual machine? Or did i do something wrong with the installation? I followed step by step the instructions written in the Readme files.

Thanks in advance!

**Comment by Abdul-Moiz** [comment]
I encountered the same issue. 
Resolved it by changing the document root in AppDelegate file.

Original: var documentRoot: String = "./webroot/"
Replaced: var documentRoot: String = <Project_Path>

And in init() method.
Original: self.documentRoot = NSUserDefaults.standardUserDefaults().stringForKey(KEY_SERVER_ROOT) ?? "./webroot/"
Replaced:  self.documentRoot = NSUserDefaults.standardUserDefaults().stringForKey(KEY_SERVER_ROOT) ?? <Project_Path>

Hope this will resolve your problem.

**Comment by kjessup** [comment]
You will need to put an index file in the webroot. With Xcode, it copies the various mustache files into the root as part of the build process, but on Linux this is not automatically done. On Linux there is a bit more manual effort required and we certainly need to document this better. The general heuristic is to copy the .mustache files from the example project into the webfoot folder which gets created in whichever working directory you are executing the perfectserver{http,fcgi} in.

**Comment by mpclarkson** [comment]
Checkout my [vagrantfile](https://github.com/mpclarkson/perfect-swift-linux/) - it should make things pretty clear on how to get everything running on ubuntu

**Comment by sumantimalsina9** [comment]
guys i am also having the same problem on my new project. 
I followed this tutorial [http://code-me-dirty.blogspot.co.uk/](url)
and i ended up with the same error which I could not fix it can u guys please help me.

<img width="536" alt="screen shot 2016-02-10 at 8 43 19 pm" src="https://cloud.githubusercontent.com/assets/10903786/12950814/1c05944c-d037-11e5-8830-6811aee1b111.png">

thanks in advance.

**Comment by ludagoo** [comment]
Add missing file to Project > Build Phases > Copy Files

Destination should be set Product Directories

Subpath to webroot

The list needs to have all the mustache or static files you have.

**Comment by sumantimalsina9** [comment]
can you give me a screenshot so i can figure it out.
i am totally new to swift.

**Comment by dsp1589** [comment]
any idea on where is webroot folder?

my executables are here ./build/debug/

**Comment by rymcol** [comment]
@dsp1589 see: https://github.com/PerfectlySoft/PerfectExample-UploadEnumerator - This is a good example of how it should look

I.e. If you executables are at ./.build/debug/ then your webroot should simply be at ./webroot/

**Comment by iamjono** [comment]
Hi all - looks like each of the issues have been addressed. Closing for now, please open a new issue for specific problems as they arise!
