### ISSUE TITLE
Cannot build on osx, make failed

### ISSUE THREAD

**Issue by tirrorex** [PerfectlySoft/Perfect#38]
Got this after running make on el capitan, did i miss something?

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "openssl/ssl.h"
        ^
/Users/zipeldiablo/Perfect/PerfectLib/linked/OpenSSL_Linux/openssl/ssl.h:146:11: note: in file included from /Users/zipeldiablo/Perfect/PerfectLib/linked/OpenSSL_Linux/openssl/ssl.h:146:
# include <openssl/e_os2.h>
          ^
/Users/zipeldiablo/Perfect/PerfectLib/linked/OpenSSL_Linux/openssl/e_os2.h:56:10: error: 'openssl/opensslconf.h' file not found
#include <openssl/opensslconf.h>
         ^
NetTCPSSL.swift:26:8: error: could not build Objective-C module 'OpenSSL'
import OpenSSL
       ^
make[1]: *** [ICU.o] Error 1
make: *** [all] Error 2

**Comment by kjessup** [comment]
The makefiles are not yet good to go on OS X. You still need to use Xcode for now.

**Comment by tirrorex** [comment]
I was using the makefile because i cannot build on xcode, example projet doesn't find perfectLib

**Comment by Begoodi** [comment]
I have the same issue with the import of perfectLib. Could you describe how to launch server on OS X under Xcode ?

**Comment by maxerogers** [comment]
Also having this issue.

**Comment by AdamSliwakowski** [comment]
Makefiles should be used on linux. But yes, I am also facing problem in XCode

**Comment by tirrorex** [comment]
Thanks for the answer, it fixed my issue

**Comment by DiveinEdu** [comment]
Just delete things about Linux
