### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by brado** [PerfectlySoft/Perfect#40]
I've spent the last two days trying to get a project with several dependencies compiled and running on Linux. The other projects I've been working with use the Swift Package Manager approach, a Package.swift definition file plus /Sources directory, which makes it very easy to link dependencies from their github repo URL. 

Perfect on the other hand uses a makefile. It would be really nice to be able to reference PerfectLib in the same manner, but it doesn't appear the project is structured to be Swift Package Manager friendly (unless I'm missing it). 

What's the prospects of getting the Perfect project structured to work with Swift Package Manager, and in the meantime, what's your recommended approach for using Perfect as a dependency for projects building on Linux? 

Thanks.

**Comment by C0deH4cker** [comment]
I believe that Perfect is purposefully not using the Swift Package Manager at this point because swiftpm currently only builds static libraries, but Perfect needs the libraries to be built dynamically.

**Comment by kjessup** [comment]
This is true - we rely on dynamic libraries in both PerfectLib and the handler modules it loads. When SPM supports dynamic libraries we will switch to that, assuming it also supports integrating arbitrary C code as we use a bit of that for bridging certain gaps (some helper functions and wrapping variadic C funcs as well). We will definitely support SPM in the handler modules. I'll add the intent for SPM support to the roadmap document and close this issue. Thanks!

**Comment by brado** [comment]
As SPM is really the only direction folks presently have for building on Linux, and thus with the handful of Swift Linux-ready projects on Github I've encountered, they are using SPM -- and that makes it really easy to build on Linux. I think what we need is some kind of doc on how to build a project on linux that is using SPM *and* linking against PerfectLib. I think that's the common Linux build scenario that's going to be encountered by anyone wanting to use PerfectLib.

**Comment by crizzwald** [comment]
Has there been any movement with SPM? I am looking to try and deploy the URL Routing example to Heroku and am trying to figure out just how to do that... Thoughts anyone?
