### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by swizzlr** [PerfectlySoft/Perfect#41]
Hi there,

I'm one of the contributors to https://github.com/swiftdocker/docker-swift. If there's any interest in vendoring a docker image containing the suite of Perfect libraries and possibly the server (though I wonder if long term a server isn't really in your interest, given that nginx etc exist) for easy development and deployment, please let me know if I can be of any assistance!

**Comment by AttilaTheFun** [comment]
@swizzlr that would be great!

**Comment by alexandros-s** [comment]
:+1:

**Comment by SeanStephens** [comment]
There have been a number of Docker images that I can see for Perfect (I starred all the ones I could find);

https://hub.docker.com/u/seanstephens/starred/

We've also started a PerfectlySoft repo for images, just to make sure there are clean and up-to-date ones moving forward.

https://hub.docker.com/u/perfectlysoft/

Thanks for all the help!
