### ISSUE TITLE
Trailing URL Variables not placed in urlVariables dictionary

### ISSUE THREAD

**Issue by iachievedit** [PerfectlySoft/Perfect#43]
I would expect `urlVariables` to contain an entry for `id` in the following case:
```
Routing.Routes["GET", "/device/{id}"]
```

It doesn't.  Adding a trailing component to the URL it does get populated:

```
Routing.Routes["GET", "/device/{id}/show"]
```

Extending further,

```
Routing.Routes["GET", "/device/{id}/show/{sub}"]
```

`sub` is not in the the `urlVariables` dictionary but `id` is.

**Comment by kjessup** [comment]
Fixed. Thank you!
