### ISSUE TITLE
WebRequest has no method for accessing body

### ISSUE THREAD

**Issue by iachievedit** [PerfectlySoft/Perfect#44]
The current implementation of `WebRequest` appears to try to assume/do too much.  Particularly in the event of POSTing `Content-type:  application/json`, I should be able to post a document body with a properly formed JSON string.  Then, in my handler I can access the body directly (what appears to be `request.connection.stdin` but that is protected) without any "intelligence" from `postParams` processing.

**Comment by kjessup** [comment]
Correct and thank you for the feedback.

I added `WebRequest.postBodyBytes` and `WebRequest.postBodyString` to provide access to this data as either [UInt8] or String, respectively.

I tested using URL Routing example & curl on the cli and was able to grab the raw data as expected.

curl --data "{\"id\":123}" http://0.0.0.0:8181/raw --header "Content-Type:application/json"

Thank you!
