### ISSUE TITLE
no such module "perfectlib"

### ISSUE THREAD

**Issue by 25564** [PerfectlySoft/Perfect#49]
main_http.swift while using XCode 7.2

Just needs the build settings modified slightly

PerfectLib -> Build Settings -> Packaging -> Defines Module

It currently defaults to No causing the error.

**Comment by kjessup** [comment]
I don't see the problem myself. It builds and runs fine with Xcode 7.2. I will make this change though.

**Comment by s0mmer** [comment]
Downloading the project, opening an example (e.g. Authenticator) and building Authenticator Server, I'm experiencing the same problem. Xcode 7.2 and Xcode 7.3 beta.
