### ISSUE TITLE
Current License Terms for the client code are unacceptable

### ISSUE THREAD

**Issue by cwoloszynski** [PerfectlySoft/Perfect#50]
Can you please put the client library code under BSD or MIT?  As it stands, the client apps will be open-sourced as I read the current license.

**Comment by cwoloszynski** [comment]
Please reconsider the terms for the client code. It makes all the client apps open-sourced.  I cannot accept that.

**Comment by SeanStephens** [comment]
We are working on further clarification, in detail. For the time being, I've merged this request with the ongoing dialogue in https://github.com/PerfectlySoft/Perfect/issues/26.

Thanks for your input! We will address the clarification. (Client apps do NOT need to be open source).

**Comment by SeanStephens** [comment]
Thanks for the feedback, it was helpful. We've switched to Apache, and your request was part of this decision. Happy coding!

https://github.com/PerfectlySoft/Perfect/issues/131
http://perfect.org/blog.html
