### ISSUE TITLE
Swift NGINX Module?

### ISSUE THREAD

**Issue by drppublic** [PerfectlySoft/Perfect#56]
A moderate feature request: Perfect has an Apache connector; it would be great to see an NGINX module too!

**Comment by groovelab** [comment]
I success to run Perfect on FastCGI with nginx.
Server Configure is below.
https://gist.github.com/groovelab/fae744207b96133ebd4a#file-your-domain-com

**Comment by InfiniteDevelopment** [comment]
Hey @groovelab would be cool to know a bit more about how you got it all set up. I want to use Swift on a project I have but dont want or need the apache headache when it comes to scaling. 

How exactly did you use perfect framework and nginx together? Thanks so much in advance!!! :)

**Comment by kjessup** [comment]
https://github.com/PerfectlySoft/Perfect/wiki/NGINX
