### ISSUE TITLE
How to run MySQLTests.swift?

### ISSUE THREAD

**Issue by lyenliang** [PerfectlySoft/Perfect#58]
How can I run MySQLTests.swift on ubuntu?

I've copied both `MySQL.so` and `MySQL.swift` to `Perfect/Connectors/MySQL/MySQLTests`.

When I execute `swift MySQLTests.swift`, I always get `error: no such module 'MySQL'`

**Comment by kjessup** [comment]
Currently building on all platforms with SPM and set to execute tests with 'swift test'.
