### ISSUE TITLE
An ExpressJs like framework.

### ISSUE THREAD

**Issue by ysholqamy** [PerfectlySoft/Perfect#59]
Hi, I am planning on developing an ExpressJS like framework using swift. I was searching for a swift NetTCP library but could not find one. I like your NetTCP implementation, it is really neat. So, could you publish it as a separate swift package? Thanks in advance

**Comment by ysholqamy** [comment]
I can put it together (the implementation and unit tests) in a package skeleton ready to publish if you wish.

**Comment by iamjono** [comment]
Hi Youssef - take a look at the module here: https://github.com/PerfectlySoft/Perfect-Net
I think that might be what you're looking for!
Thanks
