### ISSUE TITLE
no umbrella header

### ISSUE THREAD

**Issue by Tangdixi** [PerfectlySoft/Perfect#62]
**Great project !**

But I have some question..  
I clone the repo and build the **_PerfectLibOSX_** target in **_Examples.xcworkspace_**.  
But then I got a warning
```
warning: no umbrella header found for target 'PerfectLibOSX', module map will not be generated
```
Is this normal?  
My Xcode is **Version 7.2 (7C68)**

**Comment by iamjono** [comment]
Hi @Tangdixi can you let us know if the issue is still remaining? 
Closing for now as I think this is affecting an older release.
Please reopen with more info as needed :)
