### ISSUE TITLE
Suggest: use tyrone-sudeium/JSONCore instead of JSON.swift

### ISSUE THREAD

**Issue by SimpleFelix** [PerfectlySoft/Perfect#69]
I tried tyrone-sudeium/JSONCore, it's Foundation free. I try serialize ["ad":[["i": -41451, "i2": 41451, "d": -42E+2, "t": true, "f": false, "n": nil, "a":[1, 2, 3, 4]], ["another":"one"]]] and it works properly.
JSON.swift still have a lot of work to make it work. I think we should just use tyrone-sudeium/JSONCore for JSON parse/serialization and focus on some other Perfect module.

**Comment by alexandros-s** [comment]
:+1:  I agree that is a good idea to depend on external sources for now and later if it is proved necessary to remove the dependency and replace it with a home brewed one. I also have a strong feeling that a JSON parser is out of the scope of this project.

**Comment by iamjono** [comment]
The specific framework you use for your own JSON transactions in Perfect is your choice - you would include as a dependancy.
As always, we welcome your comments and feedback :)
