### ISSUE TITLE
Consistent swift coding style

### ISSUE THREAD

**Issue by cristeahub** [PerfectlySoft/Perfect#7]
Taken from this reddit comment:: https://www.reddit.com/r/swift/comments/3ttu9u/serverside_swift_is_here_its_perfect/cx9hrpc

```
Nice work!
I have one suggestion though - be more consistent wrt to code conventions. For example, top
level constants (from one module) are defined in
- lowercase snake case
- uppercase snake case
- camelCase
...
```
by [20DCCD77-E82E-4045-A](https://www.reddit.com/user/20DCCD77-E82E-4045-A)

I would suggest using https://github.com/raywenderlich/swift-style-guide as your style guide. At least as a mold for a style guide. It seems to be very good.

**Comment by net** [comment]
+1

**Comment by iamcam** [comment]
+1 on the Ray Wenderlich style guide for inspiration.

**Comment by DJNgoma** [comment]
Realm even has a linter as well :D 
https://github.com/realm/SwiftLint

**Comment by MoathOthman** [comment]
+1 for Ray wanderlich swift guide

**Comment by narup** [comment]
:+1:

**Comment by iamjono** [comment]
I'm a big believer in the Ray Wenderlich style guide too... However I'm closing this issue as it's been hanging around for a while and a lot of code's been updated to conform to conventions :)
Thanks!
