### ISSUE TITLE
Laravel style controllers

### ISSUE THREAD

**Issue by tannernelson** [PerfectlySoft/Perfect#77]
I set up a typical JSON API route using Perfect. 

```swift
public func PerfectServerModuleInit() {
    Routing.Handler.registerGlobally()
    
    Routing.Routes["GET", "heartbeat"] = { response in
        return HeartbeatHandler()
    }
}

class HeartbeatHandler: RequestHandler {
    
    func handleRequest(request: WebRequest, response: WebResponse) {
        response.addHeader("Content-Type", value: "application/json")
        let encoder = JSONEncode()
        
        do {
            let data = try encoder.encode(["lub": "dub"])
            response.appendBodyString(data)
        } catch {
            response.setStatus(500, message: "Could not create data")
        }
        
        response.requestCompletedCallback()
    }
    
}
```

Though it works well, this is very verbose. It would be nicer if Perfect took some inspiration from Laravel like so.

Routes.swift
```swift
Route.get("heartbeat") { request in 
    return HeartbeatController().index(request)
}
```

HeartbeatController.swift
```swift
class HeartbeatController: Controller {
    func index(request: Request) -> AnyObject {
        return ["lub": "dub"]
    }
}
```

This wouldn't be hard to implement, but I'm wondering if something like this is in the scope of Perfect, or if it's something that should be built as a separate project. 

I'd be very interested in working on this.

**Comment by kaandedeoglu** [comment]
+1 from me, this kind of syntax is very convenient for simple responses.

For reference there are a few Swift frameworks that support this kind of syntax, namely:

[Vapor](https://github.com/tannernelson/vapor)
[Frank](https://github.com/nestproject/Frank)
[Zewo's Router](https://github.com/Zewo/Router)
