### ISSUE TITLE
HTTP Server, unicode folder name

### ISSUE THREAD

**Issue by tylerlong** [PerfectlySoft/Perfect#86]
I followed this example to create my demo app: https://github.com/PerfectlySoft/Perfect/blob/master/PerfectServer/main_http.swift

HTTP Server to host a static website. This static website contains a folder containing unicode characters, example:  `/中文/index.html`

Try to access `http://localhost:8181/中文/index.html`

Error: `The file "/%E4%B8%AD%E6%96%87/index.html" was not found.`

GitHub Pages does support this case. Deploy this static website to GitHub Pages and there is no similar issue.  GitHub Pages support both `/中文/index.html` and `/%E4%B8%AD%E6%96%87/index.html`. You can use either to access the page.

Let me know if you need any more details. 

Thank you for your wonderful work!

**Comment by iamjono** [comment]
@tylerlong I'm closing this issue as @SimpleFelix has submitted a PR which has been accepted and addresses your problem. Thanks!
