### ISSUE TITLE
Tutorial/Guide coming?

### ISSUE THREAD

**Issue by asterhouse** [PerfectlySoft/Perfect#92]
I'm looking at the examples and none of them really help me to get started on my own project. I wondered if you are planning to release any tutorials or get started guides. Preferably on a REST API. I love that Swift is so close in performance to C++ and I would love to build my new app with this library but the learning curve seems to be too steep.

**Comment by getaaron** [comment]
If someone more knowledgeable about this product could provide a tutorial outline with code samples, I'd be happy to flesh it out into a full guide.

**Comment by BleuGamer** [comment]
I'd be for this as well. I might dig into the source this coming week.

**Comment by alexandros-s** [comment]
https://github.com/PerfectlySoft/Perfect/issues/98

**Comment by lokinfey** [comment]
I write perfect guideline in Chinese http://blog.csdn.net/kinfey/article/details/50644752 Welcome to read it .

**Comment by iamjono** [comment]
Hi George, Aaron, Lance, and anyone else looking for this!
Alexandros's guide is great, as is Kinfey's as I am told.
We are also working on adding "Quick Start" sections to ReadMe's and creating more sample projects - as well as some nice shiny tools to help get you started easier.
For now I am going to close this issue, but please watch for announcements on the Perfect.org site, as well as Gitter and Twitter.
Thanks
