### ISSUE TITLE
Make request.postParams a dictionary instead of an Array of tuples

### ISSUE THREAD

**Issue by johnlinvc** [PerfectlySoft/Perfect#96]
Currently the postParams in request object is having a type of `Array<(String, String)>`, which is hard to find a particular value by it's key. In many web frameworks, the POST params is a dictionary(hash), including Rails/sinatra/tornado and php. I suggest to change it to a dictionary of type `Dictionary<String, String>` for easier access.

**Comment by eimantas** [comment]
:+1: The `Array<(String, String)>` also does not support nested parameters like `foo[bar][baz]=jox`

**Comment by kjessup** [comment]
POST and GET parameters can contain multiple values with the same key. Additionally, the order of the parameters is meaningful and so you can't simply aggregate them into a [String:[String]] structure.

WebRequest already contains the following functions which let you pull value(s) by key:

/// Returns the first GET or POST parameter with the given name
public func param(name: String) -> String?

/// Returns the first GET or POST parameter with the given name
/// Returns the supplied default value if the parameter was not found
public func param(name: String, defaultValue: String) -> String

/// Returns all GET or POST parameters with the given name
public func params(named: String) -> [String]?

**Comment by johnlinvc** [comment]
Yes, it's possible that parameter can contain multiple values with the same key. But there's no spec on how to deal with values with the same key, different servers can have different behavior. On page 9 of [this report](https://www.owasp.org/images/b/ba/AppsecEU09_CarettoniDiPaola_v0.8.pdf) shows how different servers handle this. PHP has last occurrence, Python(mod_wsgi) has first occurrence.

For the most frequent use cases, parameters usually have unique keys. And just like @eimantas said, it's hard to handle nested parameter in current interface.

**Comment by kjessup** [comment]
I'm closing this issue with the following reasons:
1. We already provide the requested functionality. That is, the ability to retrieve a GET/POST parameter by name with `param(name: String) -> String?`
2. Switching the internal storage to be a Dictionary removes functionality. That is, the ability to have multiple key/value pairs with the same name.
3. Storing GET or POST parameters in a Dictionary, particularly one you do not have explicit source control over, opens the system up to hash collision DoS attacks.
