### ISSUE TITLE
How to start Perfect Server in Xcode

### ISSUE THREAD

**Issue by lokinfey** [PerfectlySoft/Perfect#98]
When I use Examples.xcworkspace and Start URL Routing project , It can open PerfectServer . But When I add Perfect template  in Xcode . I create project in template . All builds well But It can not start PerfectServer. Can you tell me how to do ?

<img width="928" alt="2016-02-06 6 42 58" src="https://cloud.githubusercontent.com/assets/4607663/12866209/7f7ce306-cd01-11e5-9ede-847f78681ef5.png">

**Comment by alexandros-s** [comment]
I just started working in a guide in [my blog](http://code-me-dirty.blogspot.co.uk/2016/02/creating-perfect-swift-server.html) it might help you a bit. It's still work in progress. 

For direct questions and help I would suggest to use the [gitter](https://gitter.im/PerfectlySoft/Perfect) channel.

Cheers

**Comment by lokinfey** [comment]
ok thx

**Comment by iamjono** [comment]
Closing, looks like this has been sorted on the other thread.
